### ISSUE TITLE
Make the CI tests for repo 

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfp-tekton#100]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]

Make the CI tests for repo, so that we can ensure the quality by basic testing, such as function user end to end cases, Pylint testing etc ... After the CI tests setup, contributor can develop test case while implement functions. Thanks.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ckadner** [comment]
Hi @jinchihe -- we do run the unit test cases with Travis/CI for each PR. 

For end-to-end testing with running pipelines on a Tekton cluster I had started to work on #28.

**Comment by jinchihe** [comment]
@ckadner Sounds Great! Thanks.
