### ISSUE TITLE
Publish kfp-tekton SDK in Pypi 

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfp-tekton#101]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]

Now usr needs to install kfp-tekton by `pip install -e ...` after cloning code from github, but sometime user would not like to download source code, just run pip to install the SDK, we should publish the SDK to Pypi, and avoid the name is used recently by others.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment]
Now the kfp-tekton can be installed by pip directly.
```
(python36) [root@jinchi1 ~]# pip install kfp-tekton
...
Installing collected packages: kfp-tekton
Successfully installed kfp-tekton-0.0.1
(python36) [root@jinchi1 ~]#
(python36) [root@jinchi1 ~]#
(python36) [root@jinchi1 ~]# pip show kfp-tekton
Name: kfp-tekton
Version: 0.0.1
Summary: KubeFlow Pipelines compiler generating Tekton YAML (instead of Argo YAML).
Home-page: https://github.com/kubeflow/kfp-tekton/
Author: kubeflow.org
Author-email: None
License: Apache 2.0
Location: /opt/python/python36/lib/python3.6/site-packages
Requires: kfp
Required-by:
(python36) [root@jinchi1 ~]#
```

**Comment by jinchihe** [comment]
/cc @animeshsingh @fenglixa 
Would you please let me know you Pypi ID so that I can add you as Maintainers for the SDK. Thanks.

We should refresh the SDK once key/big features are done.

**Comment by fenglixa** [comment]
@jinchihe Great to know you are on this.
My ID is same as github (fenglixa)

**Comment by ckadner** [comment]
@jinchihe -- I am not sure we are ready to publish on PyPi yet. Should we not wait until we have a stable release? If we do already want to have the PyPi package public, then we should add some documentation on the landing page make it clear that this is still experimental.

**Comment by jinchihe** [comment]
@ckadner Yeah, this is 0.0.1 version and consistent with github source code, user would know that. We should publish that to reserve that name in Pypi. If someone used `ktp-tekton`, we need update the name when publish, I've been there before for my project, and it's not good to rename ...

By the way, if you like, please let me know you Pypi id, I will add you as maintain, thanks.

**Comment by ckadner** [comment]
> ...please let me know you Pypi id, I will add you as maintain ...

https://pypi.org/user/ckadner/

Thanks @jinchihe

**Comment by Tomcli** [comment]
Thanks @jinchihe, can you also add me as a maintainer as well? https://pypi.org/user/tomcli/

**Comment by jinchihe** [comment]
@ckadner and @Tomcli Done, thanks!
