### ISSUE TITLE
Found more official repo for "kubectl-wrapper"

### ISSUE THREAD

**Issue by vincent-pli** [kubeflow/kfp-tekton#102]
/kind question

**Question:**
There still one thing for resourceOp, I talked with @vdemeester from tekton, he think the catalog should only maintain the yamls stuff, the source code will make the repo mass to manage.

So we still need find a more official repo.

Another choice is submit the image to a official repo.
@animeshsingh @Tomcli @ckadner @fenglixa

**Comment by Tomcli** [comment]
Thanks, @vincent-pli and @vdemeester, is there any common practice or recommendation on where we should host and maintain the source code? 

One approach could be putting the source code in this kfp-tekton, but the CI/CD process could get complicated over time as we might be adding more microservices for integration during our next phrase.

**Comment by fenglixa** [comment]
In my opinion, if there is no better choice, we should put it here, as it's true we are using it, and need to keep maitaining if any issues found.

**Comment by vincent-pli** [comment]
I think I agree with @fenglixa , for now, there is no right repo in `tekton` side, we can maintain in `kfp` temporary and contribute back to `tekton` later.

**Comment by Tomcli** [comment]
@animeshsingh @ckadner are you guys fine with storing the `kubectl-wrapper` source code in this Repo? We can create a subdirectory for this and have some go CI only run under that subdirectory.

**Comment by ckadner** [comment]
> @animeshsingh @ckadner are you guys fine with storing the `kubectl-wrapper` source code in this Repo? We can create a subdirectory for this and have some go CI only run under that subdirectory.

I'm not a big fan of that but it seems like this is our only option at this point

**Comment by Tomcli** [comment]
@animeshsingh Want to double check with you is it okay to put the `kubectl-wrapper` source code in our `kfp-tekton` repo until Tekton has a better place to maintain it?

**Comment by Tomcli** [comment]
Hi @vincent-pli, in our scrum today we all agreed to put the kubectl-wrapper source code under this `kfp-tekton` repo. Can you create a PR to move the kubectl-wrapper code under a directory such as `/tekton-catalog/kubectl-wrapper`? Thank you for your contribution!

**Comment by vincent-pli** [comment]
@Tomcli 
Sure, will work on it soon.
