### ISSUE TITLE
Clarify building from Tekton master in sdk/README

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#109]
https://github.com/kubeflow/kfp-tekton/blame/master/sdk/README.md#L23
> In order to use parameter passing from task outputs into condition parameters Tekton must be built from master. 

`master` will continue to change, we need to add the commit and date or the PR that brought the feature into Tekton and the expected release that has it

Also, how to build Tekton from master? Can we point to instructions or quickly describe it here.

Maybe a better way would be to describe that certain features are "cutting edge" and add a new section that lists those features used in the compiler and what commit/PR/release in Tekton it depends on.

**Comment by drewbutlerbb4** [comment]
As of this morning, it seems that the tekton folks have decided to use https://github.com/tektoncd/pipeline/pull/2477 in their next release and have added it to v0.11.x.

I can still add a section about building from master, but it seems the "Cutting Edge" section may no longer be needed (for now at least).

**Comment by Tomcli** [comment]
I think the cheery pick fixes will come in for the next v0.11.3 release. Building from Tekton master section is still nice to have because we will have more features that need to pull from master.
