### ISSUE TITLE
Generated Tekton steps have no name field.

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#11]
The new Tekton compiler didn't add any name to the Tekton steps. Thus, the pipeline is returning the following errors. 
```
Error from server (InternalError): error when creating "pipeline.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: invalid value "": taskspec.steps.name
Task step name must be a valid DNS Label, For more info refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
```

**Comment by vincent-pli** [comment]
@Tomcli 
Actually, in the latest `tekton` the `name` is not required, anyway, I added it since it will be more friendly to end user when checking the status/log.

**Comment by Tomcli** [comment]
Thank you @vincent-pli, are you using tekton 0.9.2 for your tests?
