### ISSUE TITLE
Allow users to specify the image for the `step-move-all-results-to-tekton-home` step

### ISSUE THREAD

**Issue by yhwang** [kubeflow/kfp-tekton#1103]
/kind feature

**Description:**
Currently, api server injects an internal step `step-move-all-results-to-tekton-home` into the `PipelineRun` to
move the tekton results. The image for that step is fixed which is `busybox`. Need a way to specify the image for that step.

**Comment by Tomcli** [comment]
The image is hard coded here, we need to expose this as a configurable env.
https://github.com/kubeflow/kfp-tekton/blob/master/backend/src/apiserver/template/tekton_template.go#L311

**Comment by C-nit** [comment]
being able to change the image pull policy that is `Always` now would also be great.

**Comment by yhwang** [comment]
@C-nit I thought about that but I didn't add that after I checked the `imagePullPolicy` default behavior:
https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting

in the change, I already use a tag version of busybox, which means the policy would be `IfNotPresent`.
