### ISSUE TITLE
Update the python SDK to use TEP-101 enhancement.

### ISSUE THREAD

**Issue by ScrapCodes** [kubeflow/kfp-tekton#1130]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
For this feature let's extend the tekton pipeline config for podtemplate to also accept `env` and add those values into the pod_template code at https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/compiler.py#L1403-L1412

**Comment by Tomcli** [comment]
current tekton pipeline config for podtemplate
https://github.com/kubeflow/kfp-tekton/blob/master/guides/advanced_user_guide.md#tekton-pipeline-config-for-podtemplate

**Comment by ScrapCodes** [comment]
Thanks @Tomcli
