### ISSUE TITLE
 Extend resourceOp warpper image to operate the list of resources

### ISSUE THREAD

**Issue by fenglixa** [kubeflow/kfp-tekton#121]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]
As discussion in the ticket https://github.com/kubeflow/kfp-tekton/issues/70 and https://github.com/kubeflow/kfp-tekton/issues/82. Tekton has been explicitly avoiding adding support for recursion and dynamic behavior. So we have to find another way for the solutions.

ResourceOps and VolumeOps are supported in kfp-tekton right now, by PR #89 , #93 and  kubectl-wrapper from @vincent-pli .

Another solution we can extend resourceOp warpper image to have additional parmeter (could be named as "parallel-loop-items") with the value of the list, support the type of [a, b, c, d] and also [{'a': 1, 'b': 2}, {'a': 10, 'b': 20}],  apply each value of the list to manifest to support this feature.
 
**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by fenglixa** [comment]
@vincent-pli @Tomcli any comments?

**Comment by Tomcli** [comment]
Hi @fenglixa, here is the tracking issue in the Tekton community https://github.com/tektoncd/pipeline/issues/2050

They have been discussing what are the cases they need to cover for the looping support such as looping with conditions, parallel vs sequential loop, etc. Adding all these use cases will be hard for the wrapper image and we won't get the logging and visual support from Tekton.

**Comment by fenglixa** [comment]
Thanks @Tomcli , It's great if tekton could support the looping parms. That's should be the final solution.
@vincent-pli, FYI. Thanks for your support!

**Comment by vincent-pli** [comment]
@Tomcli @fenglixa That great to hear that, thanks.

**Comment by Tomcli** [comment]
/close
will wait for tekton loop support
