### ISSUE TITLE
Where is the source code for wait_for_run_completion?

### ISSUE THREAD

**Issue by diegolovison** [kubeflow/kfp-tekton#1223]
/kind question

**Question:**
Where is the source code for `wait_for_run_completion`?

**Description:**
Hello,

I am working on an integration test. I have the following:
```
print(kfp_tekton.__version__)
'1.5.3'
```
My code is doing the following
```
my_pipeline = ....
result = client.create_run_from_pipeline_func(pipeline_func=my_pipeline, arguments={})
client.wait_for_run_completion(result.run_id, 2 * 60)
```

I am looking at: https://github.com/kubeflow/kfp-tekton/blob/1.5.x/sdk/python/kfp_tekton/_client.py
I can't see the method. Where is it?

Thanks,

**Comment by Tomcli** [comment]
@diegolovison The client function is located over here.
https://github.com/kubeflow/pipelines/blob/sdk/release-1.8/sdk/python/kfp/_client.py#L1234

For KFP-Tekton, we developed the client's compiler, UI, and backend to work on Tekton and Openshift pipelines. But for all the shared logic we are pulling from the kfp inherent package. kfp.Client
[kfp.Client](https://github.com/kubeflow/kfp-tekton/blob/1.5.x/sdk/python/kfp_tekton/_client.py#L27)

**Comment by Tomcli** [comment]
Let me update the sdk to handle the new status from Tekton. The status from API is directly pulled from Tekton status so we should update the sdk for that function as well.
