### ISSUE TITLE
Emergency dependency patch needed to allow kfp 1.8.22 for breaking cython/pyyaml change

### ISSUE THREAD

**Issue by imiller445** [kubeflow/kfp-tekton#1291]
/kind bug

**What steps did you take and what happened:**
kfp-tekton cannot be installed on python 3.10 due to an update to cython over the weekend that broke pyyaml. kfp has addressed this in 1.8.22 (allowing pyyaml < 7 but specifically 6.0.1), but kfp-tekton restricts the upper version of kfp supported to 1.8.21. 

Corresponding KFP issue: https://github.com/kubeflow/pipelines/issues/9745

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
Hi @imiller445, we addressed this issue too in the kfp-tekton sdk 1.7.1 release. Do you want us to also back patch it to older kfp-tekton sdk release as well?

**Comment by imiller445** [comment]
This was addressed in 1.7.1. Thanks!
