### ISSUE TITLE
Custom image for compiler template

### ISSUE THREAD

**Issue by diegolovison** [kubeflow/kfp-tekton#1316]
https://github.com/kubeflow/kfp-tekton/blob/d20c7b9ff110a26d59dfdef05bc1a11631b402ca/sdk/python/kfp_tekton/compiler/compiler.py#L95

```
The step "main" in TaskRun "conditional-execution-pipeline-9eb05-condition-1" failed to pull the image "". The pod errored with the message: "Back-off pulling image "python:alpine3.6"."
```

**Comment by Tomcli** [comment]
The issue should be fixed in 1.5.5 sdk. You can checkout how to change the condition image name at 
https://github.com/kubeflow/kfp-tekton/blob/v1.5.5-sdk/guides/advanced_user_guide.md#tekton-pipeline-config-for-podtemplate
`set_condition_image_name()`

**Comment by diegolovison** [comment]
My current code is
```python
        pipeline_conf = TektonPipelineConf()
        pipeline_conf.set_condition_image_name('registry.redhat.io/ubi8/python-39@sha256:3523b184212e1f2243e76d8094ab52b01ea3015471471290d011625e1763af61')
        result = client.create_run_from_pipeline_func(
            pipeline_func=pipeline, arguments={}, pipeline_conf=pipeline_conf
        )
```

and if failed because
![image (14)](https://github.com/kubeflow/kfp-tekton/assets/687311/427ee927-bc51-4807-83f0-b641f7fa8af5)


Debugging, I found that `_get_super_condition_template` is called using `self.condition_image_name` instead using `condition_image_name`
![image](https://github.com/kubeflow/kfp-tekton/assets/687311/6934839a-c135-42c3-9a2a-c8f9f14324d8)

The `condition_task_spec` will be:
```
{'results': [{'name': 'outcome', 'type': 'string', 'description': 'Conditional task outcome'}], 'params': [{'name': 'operand1'}, {'name': 'operand2'}, {'name': 'operator'}], 'steps': [{'name': 'main', 'command': ['sh', '-ec', 'program_path=$(mktemp); printf "%s" "$0" > "$program_path";  python3 -u "$program_path" "$1" "$2"'], 'args': ['import sys\ninput1=str.rstrip(sys.argv[1])\ninput2=str.rstrip(sys.argv[2])\ntry:\n  input1=int(input1)\n  input2=int(input2)\nexcept:\n  input1=str(input1)\noutcome="true" if (input1 $(inputs.params.operator) input2) else "false"\nf = open("/tekton/results/outcome", "w")\nf.write(outcome)\nf.close()\n', '$(inputs.params.operand1)', '$(inputs.params.operand2)'], 'image': 'python:3.9.17-alpine3.18'}]}
```

**Comment by Tomcli** [comment]
In our Tekton compiler, we have the argument `tekton_pipeline_conf=pipeline_conf` to specify Tekton related config. Unfortunately we didn't have it under the `create_run_from_pipeline_func` function in 1.5.5. If you want we can open an PR to add this feature.

**Comment by diegolovison** [comment]
Yes, please. After the commit if could also generate 1.5.6

**Comment by amadhusu** [comment]
@Tomcli Just following up to @diegolovison's question. Could you please generate 1.5.6 after the commit?

**Comment by Tomcli** [comment]
Sure I will do that once I have the fix it. We were busy with finalizing kfp 2.0 and Tekton v1 API migration last week. Hopefully I should able to patch it in all master, 1.7, 1.6, and 1.5 branch.

**Comment by Tomcli** [comment]
We published the 1.5.6 and 1.7.2 sdk to address this issue. Let us know if you still have trouble using the tekton config.

**Comment by Tomcli** [comment]
You should able to do it with 
```
        pipeline_conf = TektonPipelineConf()
        pipeline_conf.set_condition_image_name('registry.redhat.io/ubi8/python-39@sha256:3523b184212e1f2243e76d8094ab52b01ea3015471471290d011625e1763af61')
        result = client.create_run_from_pipeline_func(
            pipeline_func=pipeline, arguments={}, tekton_pipeline_conf=pipeline_conf
        )
```

**Comment by diegolovison** [comment]
Tested with 1.5.6 and looks good.
Thanks

**Comment by HumairAK** [comment]
> We published the 1.5.6 and 1.7.2 sdk to address this issue. Let us know if you still have trouble using the tekton config.
thanks @Tomcli , can we get this in 1.6.x as well?

**Comment by Tomcli** [comment]
@HumairAK cherrypicked the pr to KFP-Tekton 1.6.7 sdk release. 1.7.x should be compatible to 1.6.x as we didn't introduce any breaking features in 1.7

**Comment by HumairAK** [comment]
@Tomcli ++ lightning fast, thank you very much!
