### ISSUE TITLE
TEKTON_BASH_STEP_IMAGE must be customized by TektonPipelineConf::set_bash_image_name

### ISSUE THREAD

**Issue by diegolovison** [kubeflow/kfp-tekton#1321]
`TEKTON_BASH_STEP_IMAGE` must be customized by `TektonPipelineConf::set_bash_image_name`

https://github.com/kubeflow/kfp-tekton/blob/6081024172f61fc9ea8ec8a095eecdc37486cfe5/sdk/python/kfp_tekton/compiler/_op_to_template.py#L37

![image](https://github.com/kubeflow/kfp-tekton/assets/687311/14a98351-1754-4f5c-a2dc-935c62918c4c)

**Comment by diegolovison** [comment]
Hello @Tomcli 
If you could give some love on this one :)

**Comment by diegolovison** [comment]
Could it be backported to 1.5 and 1.6?
Also, a new release will be required.

**Comment by Tomcli** [comment]
I patched the pr to 1.5.x, 1.6.x, and 1.7.x branch and cut the new release on pypi 
https://pypi.org/project/kfp-tekton/#history
