### ISSUE TITLE
TektonPipelineConf::set_bash_image_name is not working

### ISSUE THREAD

**Issue by diegolovison** [kubeflow/kfp-tekton#1335]
Using 1.5.7 I have the following
```python
        default_image = 'registry.redhat.io/ubi8/python-39@sha256:3523b184212e1f2243e76d8094ab52b01ea3015471471290d011625e1763af61'
        pipeline_conf = TektonPipelineConf()
        pipeline_conf.set_condition_image_name(default_image)
        pipeline_conf.set_bash_image_name(default_image)
```
```python
        result = client.create_run_from_pipeline_func(
            pipeline_func=pipeline, arguments={
                'mlpipeline_minio_artifact_secret': mlpipeline_minio_artifact_secret
            }, pipeline_conf=pipeline_conf
        )
```

![image](https://github.com/kubeflow/kfp-tekton/assets/687311/6097069e-06da-457e-9aa6-188b5c1f7540)

![image](https://github.com/kubeflow/kfp-tekton/assets/687311/95a2fe53-8614-4088-8a51-91534f70d43c)

![image](https://github.com/kubeflow/kfp-tekton/assets/687311/84318387-17a8-46c8-a167-0acba1052036)

**Comment by diegolovison** [comment]
Related to: https://github.com/kubeflow/kfp-tekton/pull/1334/files , https://github.com/kubeflow/kfp-tekton/issues/1321

**Comment by diegolovison** [comment]
Failing with:

![image](https://github.com/kubeflow/kfp-tekton/assets/687311/86865f2a-7031-466e-a91e-d23532865552)

**Comment by Tomcli** [comment]
@diegolovison you should set the config with `tekton_pipeline_conf=pipeline_conf` since we are trying to extend but not modify the original DSL input.

```
        result = client.create_run_from_pipeline_func(
            pipeline_func=pipeline, arguments={
                'mlpipeline_minio_artifact_secret': mlpipeline_minio_artifact_secret
            }, tekton_pipeline_conf=pipeline_conf
        )
```


https://github.com/kubeflow/kfp-tekton/blob/master/guides/advanced_user_guide.md#tekton-pipeline-config-for-podtemplate

**Comment by diegolovison** [comment]
I changed from `pipeline_conf=pipeline_conf` to `tekton_pipeline_conf=pipeline_conf`

![image](https://github.com/kubeflow/kfp-tekton/assets/687311/43fd8afc-eb0d-4608-b944-ae1ab646674f)

The following started working
![image](https://github.com/kubeflow/kfp-tekton/assets/687311/18dc597e-1bdf-4a13-8771-82a6e5eb2354)

But the step `copy-results-artifacts` is not working
In the class `kfp_tekton/compiler/_data_passing_rewriter.py` there are multiple calls to `_get_base_step` that is not sending the configured bash image
![image](https://github.com/kubeflow/kfp-tekton/assets/687311/93bb6f3a-1573-41e3-b088-ece1daef253b)

**Comment by diegolovison** [comment]
Could you please backport to 1.6 and generate a new release?

**Comment by Tomcli** [comment]
pushed new releases to all the release branches.
