### ISSUE TITLE
Verify generated Tekton YAML

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#137]
/kind feature

**Description:**
After [upgrading to KFP SDK version 0.5.0](#135) we took over some code to:
- verify the variables resolution in the parameters of the generated compiled workflow and 
- lint the generated Tekton YAML (syntax verification)
 
That code is commented out as a guide just to serve as a guide for the appropriate Tekton specific implementation. 

We should implement the method `kfp_tekton.compiler.compiler._validate_workflow` when time permits to catch problems with the Tekton YAML before a pipeline gets deployed.

**Additional information:**
_Originally posted by @ckadner in https://github.com/kubeflow/kfp-tekton/pull/135_

**Comment by ckadner** [comment]
@afrittoli -- does Tekton have a CLI tool to parse and verify the YAML locally (before deploying it to the cluster)?

**Comment by ckadner** [comment]
@afrittoli -- is there a tool or some programmatic way to verify a given Tekton YAML is valid and compliant with the specified API version?
Currently I apply my compiled Tekton YAML to a Kubernetes cluster with Tekton deployed on it and look for errors. That approach works on a one-by-one basis or in end-to-end test cases but it does not work as part of the compiler code.

**Comment by NikeNano** [comment]
There are some validation used [here](https://github.com/tektoncd/pipeline/blob/858305d73b806583f9592dd166fdd360f5844423/pkg/apis/pipeline/v1beta1/pipeline_validation.go) for tekton pipelines. I have tried to check for any CLI validation but can't find any. @ckadner

**Comment by NikeNano** [comment]
I could start to look in to the pipeline validation, will try to do it in steps and see how the validation is done in the tekton repo.

**Comment by ckadner** [comment]
@NikeNano -- thanks for helping out on this task. I was really hoping for a CLI that allows to validate Tekton pipelines since I do not want us to duplicate (or refashion) Golang code from Tekton in this repo. This would inevitably go out of sync.

Maybe we could advocate for (or contribute) a small executable wrapper around the Tekton [`pipeline_validation`](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/pipeline/v1beta1/pipeline_validation.go) and include the validation for `PipelineRun`, `Task`, `Condition`, ...

**Comment by NikeNano** [comment]
Good point!
 
> Maybe we could advocate for (or contribute) a small executable wrapper around the Tekton [`pipeline_validation`](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/pipeline/v1beta1/pipeline_validation.go) and include the validation for `PipelineRun`, `Task`, `Condition`, ...

I will look into making it as an contribution to tekton that we can reuse!

**Comment by NikeNano** [comment]
Based upon the discussion [here](https://github.com/tektoncd/cli/issues/999) it currently is not suiting for the Tekton cli tool. But I guess we could still pursue a small executable to validate the the resources you mention @ckadner

**Comment by evan-hataishi** [comment]
@ckadner I was just looking for this as well. What a coincidence that you had already opened an issue for this feature, and it was the first link I clicked on 😀. It's pretty annoying to deploy a pipeline just to figure out whether the yaml is valid or not 😢.
