### ISSUE TITLE
Update compiler to use taskRun podTemplate spec

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#146]
/kind feature
/help-wanted

**Description:**

Thanks to @NikeNano's PR https://github.com/tektoncd/pipeline/pull/2389, taskRun podTemplate spec is now available in Tekton pipelineRun.

Current implementation: https://github.com/kubeflow/kfp-tekton/blob/master/sdk/FEATURES.md#affinity-node-selector-and-tolerations 
Code: https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/compiler.py#L312-L319

Above is our current implementation to use pipelineRun podTemplate spec. Our goal is to migrate this to use taskRun podTemplate spec so it has the same behavior as Argo.

**Comment by NikeNano** [comment]
@Johanwork maybe this would be something for you? I can help out.
