### ISSUE TITLE
Validate identifiers

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#151]
- identifiers have a 63 character limit
- consistently replace under score characters `_` with dashes `-` (`_` -> `-`)

**Comment by Tomcli** [comment]
nit: identifiers should have 57 character limit because the API also needs to append a 6 character uuid for each new PipelineRun.

**Comment by ckadner** [comment]
> nit: pipeline name identifiers should have 57 character limit because the API also needs to append a 6 character uuid for each new PipelineRun.

I was planing to change the general code in `_sanitize_k8s_name` to add a parameter for `max_length` with a default of `63` in accordance with [K8S Label and Name Rules](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names)

IMO, when the API needs to append a UUID, it should truncate the name/label if necessary since not all names/labels need to reserve "space" for those extra characters
