### ISSUE TITLE
Support log archive to S3 storage.

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#161]
/kind feature

**Description:**
Argo has support for archiving logs to S3. The UI and cache server then take those information to display the logs or pass it to other artifacts. Since Tekton doesn't support archive logs, we need to have an extra step/sidecar to aggregate logs from main container and sent it to S3.

Design doc summary: https://docs.google.com/document/d/14UF7b5-4YnqssaR2Kkfo0GWSx5uLHF4wHSbyREz73-g/edit

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
There were some cloud events for pipeline resource CRD that can archive logs. However, We don't see any plan for pipeline resource moving to v1beta1 API. It would be better to create with some Tekton catalog container or create our own.

**Comment by Tomcli** [comment]
FYI: https://github.com/tektoncd/pipeline/blob/master/tekton/README.md#run-the-pipeline

**Comment by Tomcli** [comment]
This is how Argo did their log archive. Because Tekton doesn't have this feature, we need an extra step or extend our artifact passing to also capture and send the logs to S3 object storage.
https://github.com/argoproj/argo/blob/master/workflow/executor/executor.go#L505-L567

**Comment by fenglixa** [comment]
I saw kubeflow/pipelines#2081 provided the capacity of achiving logs to S3, which was controled by severl env variables from UI.

For kfp-tekton: 
**1. What's the signal of enabling archive logs, how to define it?
2. Any kfp case could be used for this issue?**

**Comment by Tomcli** [comment]
sorry @fenglixa I missed your message easier. We can add a flag for this feature similar with how we done with artifacts. https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/main.py#L53-L55

This feature came from Argo, which later get adopted with the kfp frontend. For Argo there's no changes to the yaml because it was done on the controller level, but Tekton doesn't have such feature so we need to embed it as part of our compiler. 

The reason we wants it because if the logs are not archive, we need to always rely on the k8s api to stream the logs which they may get lost after a kubelet reset. Also it's always better to persist logs in a separate storage for production, so we can clean up the completed pods without worries losing the log information.

This is something a bit difficult to test, but the log file should also be treated as an artifact file and annotated here for metadata tracking. https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/compiler.py#L319-L320

We can extend this as an example, if log archive is enabled. Then we also copy the log file to the same path as the other artifacts. Here we only need to log the `main` container so it can align with the Argo behavior.
https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/parallel_join_with_artifacts.yaml

**Comment by fenglixa** [comment]
Great! Thanks @Tomcli , very clear!

**Comment by fenglixa** [comment]
Tekton discussed this topic before:
https://github.com/tektoncd/pipeline/issues/1155#issuecomment-530014356
From discussion, Fluentd and sidecars is the proper solution to query for log output based on the Pipeline, PipelineRun, Task, or TaskRun.
But based on my investigating, seems it's not a good choice.

**Another solution**, tekton has it's own dogfooding to collect logs: https://github.com/tektoncd/plumbing/tree/master/pipelinerun-logs and made some progress on https://github.com/tektoncd/pipeline/issues/454 which is all about having a "results store" which goes beyond logs. We may could use it.

**Comment by animeshsingh** [comment]
cc @afrittoli @pritidesai please see above  - and investigate if we have any recommendations/roadmap direction from Tekton?

**Comment by Tomcli** [comment]
Tekton Dogfood can work, but the only concern I have is this will introduce Tekton Triggers and pipeline resource to our pipelines where pipeline resource is still using the alpha api as I mentioned above. Although I do see there's resourceSpec in the latest release, so probably won't be as bad as the condition work around that we have.

**Comment by Tomcli** [comment]
@fenglixa Can you describe a little bit more on the cons with the fluentd investigation? The Tekton community didn't explicitly say fluentd is not a good option. There was an proposal in the Tekton community that suggested to use fluentd a while ago, but it didn't get accepted because Tekton leaves it open to the cloud provider.
https://github.com/eddycharly/dashboard/blob/external-logs/docs/walkthrough/walkthrough-logs.md

**Comment by fenglixa** [comment]
@Tomcli @animeshsingh , I drafted a document which could successful collect the tekton pipeline logs to S3, you can get it from here:
https://github.com/fenglixa/kfp-tekton/blob/s3_doc/pipeline_logging_output_s3.md

**Comment by fenglixa** [comment]
pipelinerun-logs requires a cluster running on GKE with "Stackdriver Kubernetes Engine Monitoring" enabled. 
@Tomcli , does it OK for us?

**Comment by fenglixa** [comment]
Try to work out the pipeline logs to S3 by the solution of fluented + finally now.
https://docs.fluentd.org/how-to-guides/apache-to-s3

**Comment by Tomcli** [comment]
@fenglixa is the `pipelinerun-logs` not able to work on IKS? Also, we don't want to use fluented for our finally approach because the Watson team said it's taking too much resources.

**Comment by Tomcli** [comment]
@fenglixa is it possible to create our own service/job to use kubectl or the tkn cli to pull the logs? Then in the finally task we can either call the service directly or trigger it using the [Tekton trigger](https://github.com/tektoncd/triggers) service. We can talk to the watson team tomorrow and see what kind of rbac permission they allow for Tekton pipeline.

**Comment by animeshsingh** [comment]
@vdemeester do we have log archival enabled with OpenShift pipelines? What's the implementation there if it exists?

**Comment by Tomcli** [comment]
Some options we already investigated. https://docs.google.com/document/d/14UF7b5-4YnqssaR2Kkfo0GWSx5uLHF4wHSbyREz73-g/edit#

**Comment by fenglixa** [comment]
Thanks @Tomcli , For you summary, per our discussion in the meeting. It should be OK if "fluentd container" + finally works for Tekton pipeline logs. I built the image of it, only 50MB, not heavy to impletment this function. 

Right now, I am still debuging/investigating the way on it now, but I think it should works for us.

```
>docker images |grep pipeline-logs
fenglixa/pipeline-logs-s3   latest               1687b70719c0        25 hours ago        50.3MB 
```

**Comment by fenglixa** [comment]
> @fenglixa is the `pipelinerun-logs` not able to work on IKS? 

Yes, it was described here: 
https://github.com/tektoncd/plumbing/tree/master/pipelinerun-logs#access-to-stackdriver

With the content:
> This app relies on access to the Stackdriver API in order to fetch log entries for a given Prow Build ID. This requires a cluster running on GKE with "Stackdriver Kubernetes Engine Monitoring" enabled.

**Comment by fenglixa** [comment]
/reopen
because still another solution is on the way.
