### ISSUE TITLE
Remove ArtifactLocation support when migrating to KFP 0.5.1

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#163]
/kind bug

**What steps did you take and what happened:**
KFP 0.5.1 has officially removed the ArtifactLocation support. So we need to remove the ArtifactLocation in kfp-tekton when we migrate to KFP 0.5.1. Otherwise it will produce an `ImportError`.

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by fenglixa** [comment]
@Tomcli I am handling input/output artifacts in `Fix big data passing` task # 63, which will hanlde all kinds of input/output artifacts.
So, could you please hold on this task, as it's part of my on-going task now. Thanks!

**Comment by Tomcli** [comment]
@fenglixa no problem, I opened this issue as a TODO for the KFP version upgrade.

**Comment by fenglixa** [comment]
Thanks @Tomcli, ArtifactLocation could be removed now, since issue #63 was done.  Not sure whether you will handle it later or any helps from my side do you need?

**Comment by Tomcli** [comment]
@fenglixa, I can take care of this. If you have time, can you take a look how we can warp our container logs and send them to the object storage? https://github.com/kubeflow/kfp-tekton/issues/161

**Comment by fenglixa** [comment]
> @fenglixa, I can take care of this. If you have time, can you take a look how we can warp our container logs and send them to the object storage? #161

OK, sure.
