### ISSUE TITLE
Sub-variables / input as JSON (like in KFP loops)

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#176]
/kind feature

**Description:**
KFP defines "sub-variables" of loop item PipelineParams, `LoopArgumentVariable`, which enables the user to access loop item as a JSON object.

Currently, KFP-Tekton seems to treat every input as a string, but JSON fields are expected to be handled too. It's a must for full support of KFP loops, but may also be beneficial for non-loop inputs.

**Additional information:**
It seems to be possible to create an additional step that would decompose JSON inputs into the requested fields.

**Passing criteria:**
The user is able to get a field / sub-variable of a static loop item, e.g:

```python
loop_args = [{'A_a': 1, 'B_b': 2}, {'A_a': 10, 'B_b': 20}]
with dsl.ParallelFor(loop_args) as item:
  op1 = dsl.ContainerOp(
    name="my-in-coop1",
    image="library/bash:4.4.23",
    command=["sh", "-c"],
    arguments=["echo op1 %s".format(item.A_a)],
  )
```
[samples/core/loop_static/loop_static.py](https://github.com/kubeflow/pipelines/blob/master/samples/core/loop_static/loop_static.py) seems to be a good test.

It would be an additional advantage if the code would be easy to refactor to apply to other kinds of PipelineParam too.

**Comment by fenglixa** [comment]
@Udiknedormin , kfp-tekton already (temp) supported static loop, same with your case, refer to the example of: https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/loop_static.py#L20

Dynamic loop refer to the ticket #82
