### ISSUE TITLE
Verify whether exit handler works after tekton finish supporting it 

### ISSUE THREAD

**Issue by fenglixa** [kubeflow/kfp-tekton#180]
As requirement from watson cases, exit handler definiation in kfp-tekton is in a hurry needed by them.
But tekton has not finish to fully support Exit handler yet.  tektoncd/pipeline#2661 is still under code reviewing.
Since the finally syntax is now supported in tekton preview mode as in the final tasks can be specified but not executed yet, I provide the PR #179 for kfp-tekton which could support exit handler defination. but not tested.
This ticket will trace for testing below yamls once tekton fully support it:
sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
sdk/python/tests/compiler/testdata/exit_handler.yaml

**Comment by Tomcli** [comment]
Done
/close
