### ISSUE TITLE
Update sdk/README after `artifact_location` example was removed

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#183]
/area docs

@Tomcli we need to update the `sdk/README.md` which refers to the removed `artifact_location` example:

https://github.com/kubeflow/kfp-tekton/tree/master/sdk#2-compile-kubeflow-pipelines-with-artifacts-enabled

```Bash
dsl-compile-tekton --py sdk/python/tests/compiler/testdata/artifact_location.py --output pipeline.yaml --enable-artifacts

kubectl apply -f pipeline.yaml -n kubeflow

tkn pipeline start custom-artifact-location-pipeline --showlog -n kubeflow
```

Related: #175

**Comment by Tomcli** [comment]
Sure I can do it
/assign
