### ISSUE TITLE
Generate long_description for PyPi based on sdk/README.md

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#185]
/kind feature

**Description:**
PyPi uses the `long_description` from `setup.py` for the documentation of the landing page of the [`kfp-tekton` project on PyPi.org](https://pypi.org/project/kfp-tekton/).

We should use the content of our `sdk/README.md` for that `long_description`.

```Python
import setuptools

with open("sdk/README.md", "r") as f:
    long_description = f.read()
    # TODO: replace relative links with absolute links

setuptools.setup(
    name="...",
    description="...",
    long_description=long_description,
    long_description_content_type="text/markdown",
    # ...
)
```
/cc @jinchihe 
/assign

**Comment by ckadner** [comment]
@jinchihe -- I will create a PR for this shortly. Would you mind making me a `Maintainer` on `TEST.pypi.org` for https://test.pypi.org/project/kfp-tekton/ so I can try out if the documentation gets rendered properly? Thank you :-)

**Comment by jinchihe** [comment]
@ckadner Done, thanks.

**Comment by ckadner** [comment]
> @ckadner Done, thanks.

Thank you @jinchihe
