### ISSUE TITLE
Investigate log archival and storage in context of KFP and Tekton

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfp-tekton#198]
Currently KFP provides mechanisms to store logs on S3 backed storage, which is a derivative and dependent on Argo's solution. What is going to be the corresponding mechanism for Tekton backend in KFP

**Comment by animeshsingh** [comment]
cc @Tomcli @fenglixa @Udiknedormin

**Comment by Tomcli** [comment]
FYI, right now we are creating a custom log achieve step within our compiler to replicate the same behavior in Argo. 
https://github.com/kubeflow/kfp-tekton/issues/161

Any additional comment are welcome.
