### ISSUE TITLE
How to contribute? 

### ISSUE THREAD

**Issue by NikeNano** [kubeflow/kfp-tekton#20]
I have done some contributions to Kubeflow and Argo before and would be happy to help out with this project. Super excited about Tekton Pipelines for Kubeflow. Where would be a good place to start contribution to kfp-tekton? 

I read the contribution.md file but, is there a plan for the work or similar? 

/Niklas

**Comment by animeshsingh** [comment]
@NikeNano 

@ckadner can point to the list of open items, and see if there is one you would want to pick and run

**Comment by ckadner** [comment]
@NikeNano -- glad to have you! There is a lot of work to share. I started an "umbrella" issue to list the tasks I was planning to work on here #18 and I just started work on #19 

I will reach out to your via the Kubeflow Slack channel :-)

**Comment by fenglixa** [comment]
@ckadner @animeshsingh, Me too, I am also interesting with Tekton Pipelines for Kubeflow, and I would like to contribute on it. Thanks!

BR
-Feng

**Comment by JohanWork** [comment]
@ckadner @animeshsingh  , I am also interested in joining the community, have previously worked together with @NikeNano  In some diffrent projects.

**Comment by ckadner** [comment]
@fenglixa @JohanWork -- I will start a `Developer Guide` document with some information about the project, code structure, dev environment setup etc and also break down some of the work that has been identified so far into individual tasks.

**Comment by animeshsingh** [comment]
thanks @ckadner - Developer guide would be great help

**Comment by animeshsingh** [comment]
@fenglixa @JohanWork @NikeNano please add your details tot he page where GSOC interested candidates are applying
https://docs.google.com/document/d/1zGwa1yAoYu5erk1ucpInxaArbQQILPCXnSaDYDK9W4c/edit?usp=sharing

We will have a kick off mail/call soon as well

**Comment by NikeNano** [comment]
Awesome!

**Comment by ckadner** [comment]
Also, please check the list of **[good first issues](https://github.com/kubeflow/kfp-tekton/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)**

Most of the work items in **[Compiler work items (#18)](https://github.com/kubeflow/kfp-tekton/issues/18)** require in-dept KFP compiler and Tekton knowledge.
