### ISSUE TITLE
How to start for GSOC ?

### ISSUE THREAD

**Issue by kalakandi** [kubeflow/kfp-tekton#22]
@animeshsingh   @ckadner  , I saw this project mentioned as a GSOC project and I am interested to work on this project. have experience in Python and Data Science. Please provide me some insight on how and where to start as an newbie and how to get further in contact with you mentors, it would be very helpful of you.

**Comment by ckadner** [comment]
see #20

**Comment by animeshsingh** [comment]
@kalakandi welcome to he project. For the folks coming here through GSOC, please register your
details on this page and we will have a kick off soon
https://docs.google.com/document/d/1zGwa1yAoYu5erk1ucpInxaArbQQILPCXnSaDYDK9W4c/edit#

**Comment by teetangh** [comment]
What all skills are required to contribute to the project apart from machine learning and deep Learning ? I want to contribute to KubeFlow as well.

**Comment by ckadner** [comment]
> What all skills are required to contribute to the project apart from machine learning and deep Learning ? I want to contribute to KubeFlow as well.

- Python
- Kubernetes
- Kubeflow Pipelines (especially the compiler internals)
- Tekton
- Argo, useful to understand certain aspects of the KFP compiler code
