### ISSUE TITLE
Regenerate "Golden" End-to-end Test Logs

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#229]
**Description:**

The end-to-end tests rely on previously generated "golden" log files to compare current log output from a pipeline run on the cluster with the log output of a previous "golden" pipeline run.

Some of the "golden" log files appear to no longer be current since several code changes have modified the log output of the pipeline runs.

**What needs to be done:**

Set up a Kubernetes cluster with Kubeflow and Tekton and regenerate the "golden" log files using the following command:

```Bash
make e2e_test GENERATE_GOLDEN_E2E_LOGS=True
```

**Additional Information:**

For the test using `ResourceOp`s to success it is required create a `ClusterRoleBinding` with `cluster-admin` to the `default` service account. Since the E2E tests are run in the `kubeflow` namespace, the `default` service account is deployed it to the `kubeflow` namespace.

Create RBAC permission by running the following command:

```Bash
cat <<EOF |kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
EOF
```

After running that command you should see this message:

```
clusterrolebinding.rbac.authorization.k8s.io/default-admin created
```

**Environment:**

* Python Version (use `python --version`): 3.5.3 and up
* SDK Version: `master`
* Tekton Version (use `tkn version`): `0.14.0` or later
* Kubernetes Version (use `kubectl version`): `0.16.0`

**Comment by moficodes** [comment]
@ckadner looking into it. 
Got a IKS k8s cluster with version 1.16 and kubeflow installed as per instruction from 
https://github.com/IBM/KubeflowDojo/blob/master/HandsOn/Deployment/kubeflow-on-iks.md

**Comment by ckadner** [comment]
@moficodes and I looked at this together and it became clear that there are more fixes required to make the end-to-end tests a little bit more robust since there is too much variation in the log output from test run to test run. 

I created PR #235 to make the log verification part of the E2E tests more tolerant of erratically appearing log lines and I added a few more options to allow running only selected tests or only those which failed during the previous run.

@moficodes -- Thank you for spending the time on digging deep into the E2E tests with me and I hope you are encouraged to help make them better and to contribute to any of the other areas of this project :-)
