### ISSUE TITLE
kfp 0.2.5 has requirement kubernetes<=10.0.0,>=8.0.0, but kubeflow-tfjob 0.1.1 has requirement kubernetes>=10.0.1 which is conflict

### ISSUE THREAD

**Issue by fenglixa** [kubeflow/kfp-tekton#23]
\# pip install sdk/python
 Stored in directory: /private/var/folders/_s/4bdbvdrs655gnsyvky53tbc40000gn/T/pip-ephem-wheel-cache-hrmrp_w8/wheels/e6/32/11/93809934762b7fa6b60993126c1f4a7f571f8aaf3145b9f764
Successfully built kfp-tekton
**ERROR: kubeflow-tfjob 0.1.1 has requirement kubernetes>=10.0.1, but you'll have kubernetes 10.0.0 which is incompatible.**
... ...

\# pip install "kubernetes>=10.0.1"
... ...
Requirement already satisfied: pyasn1>=0.1.3 in /Users/fengli/venv/lib/python3.6/site-packages (from rsa<4.1,>=3.1.4->google-auth>=1.0.1->kubernetes>=10.0.1) (0.4.8)
**ERROR: kfp 0.2.5 has requirement kubernetes<=10.0.0,>=8.0.0, but you'll have kubernetes 11.0.0 which is incompatible.**

**Comment by ckadner** [comment]
@fenglixa -- we recommend to install the KFP-Tekton compiler into an isolated `virtual environment` to avoid any such version conflicts. Did you do this step?

https://github.com/kubeflow/kfp-tekton/tree/master/sdk#steps


>1. Setup Python environment with Conda or a Python virtual environment:
>```Bash
>    python3 -m venv .venv
>    source .venv/bin/activate
>```

...or you could use **Conda**

**Comment by ckadner** [comment]
@fenglixa -- did you get a chance to retry this setup in a virtual environment?

**Comment by fenglixa** [comment]
@ckadner  I found the root-cause, that I am using an old venv which was installed kubeflow-tfjob 0.1.1. uninstall it, then everything is OK now.

Great thank you for your quick response! I will close this issue then.

BR
-Feng
