### ISSUE TITLE
UI needs to support the new status for Tekton v0.14

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#234]
/kind bug

**What steps did you take and what happened:**

The latest Tekton introduced few new status for cancelling the pipeline. So we need to update the KFP frontend to map `PipelineRunCancelled` and `PipelineRunCouldntCancel`  as `terminated`. 

/assign @drewbutlerbb4 

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by drewbutlerbb4** [comment]
@Tomcli what is a way to produce a `PipelineRunCanceled` and `PipelineRunCouldntCancel` status?
