### ISSUE TITLE
List of wanted Tekton features

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#242]
/kind feature

**Description:**
Tracking issue for list of wanted Tekton features on KFP:
1. Looping and recursion https://github.com/kubeflow/kfp-tekton/issues/82
2. Conditions for v1beta1 (done)
3. A more mature concept of artifacts. https://github.com/kubeflow/kfp-tekton/issues/241
4. Community support for log archive. https://github.com/kubeflow/kfp-tekton/issues/161 (lower priority) 

Additional wanted features:
5. Pipeline checkpoints https://github.com/kubeflow/kfp-tekton/issues/264

**Comment by pritidesai** [comment]
> Conditions for v1beta1

The proposal is in `proposed` state and will be moved to `implementable` after adding more details if necessary (nothing outstanding at this time):
https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md

The proposal is to allow a task to be executed if all of the specified `Guards` evaluate to `true`. `Guards` can be specified using `when` statements. Guards operate on params of that specific task or task results of parent tasks. The same proposal also includes a `PipelineTask` level clause `continueAfterSkip` to continue execution even if the guarded task was not executed to continue executing rest of the tasks in the pipeline.

**Comment by pritidesai** [comment]
> Looping and recursion #82

[Design](https://docs.google.com/document/d/1P8gse1TCxJEDnj9oonl-_l3T4n2uO15bqbon4lHWD1Q/edit) is WIP and expected to have a TEP proposal based on this design doc.

**Comment by pritidesai** [comment]
> A more mature concept of artifacts. #241

https://docs.google.com/document/d/1p8zq_wkAcwr1l5BpNQDyNjgWngOtnEhCYEpcNKMHvG4/edit#heading=h.ynspny37nwt9

**Comment by Tomcli** [comment]
> > A more mature concept of artifacts. #241
> 
> https://docs.google.com/document/d/1p8zq_wkAcwr1l5BpNQDyNjgWngOtnEhCYEpcNKMHvG4/edit#heading=h.ynspny37nwt9

Thanks @pritidesai, the proposal looks great but all of those features are still letting the client decide which image they want to inject. We are more looking for a solution build on the server/controller side where the admin should dictate which image should be used for artifacts. We added few comments in the design docs and let's see how far we can go from there.
