### ISSUE TITLE
Swap PVC for volumeClaimTemplate in _data_passing_rewriter.py

### ISSUE THREAD

**Issue by Hachimaki** [kubeflow/kfp-tekton#254]
/kind feature
/area sdk
/area testing

**Description:**
Part of to #230 - SDK TODO for new contributors

Per the work being done in #181, the use of PVC should be removed to use the `volumeClaimTemplate` if the version of Tekton being used is >= 0.12.

**Additional information:**
Current references are [here](https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py#L310) and [here](https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py#L534)

**Comment by Tomcli** [comment]
/close
done by #309
