### ISSUE TITLE
Replace the image of kubeclient with the official image from Tekton

### ISSUE THREAD

**Issue by Hachimaki** [kubeflow/kfp-tekton#256]
/kind feature
/area sdk
/area testing

Description:
Part of #230 - SDK TODO for new contributors

Per [_op_to_template#104](https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/_op_to_template.py#L104), the image of kubeclient referenced should be replaced with an official image from Tekton.  Check if a comparable image is available and swap the reference to the official image.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by aburns7** [comment]
I am going to work on this.
