### ISSUE TITLE
Pull default values for _process_output_artifacts from the KFP configmap once integrated

### ISSUE THREAD

**Issue by Hachimaki** [kubeflow/kfp-tekton#257]
/kind feature
/area sdk
/area testing

Description:
Part of #230 - SDK TODO for new contributors

A few parameters in [_process_output_artifacts](https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/_op_to_template.py#L293) are being set from arguments passed into the function.  These should be pulled from the configmap once they are available for default values and then overwritten by the current args.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
done in #281 
/close
