### ISSUE TITLE
Add Tekton integration tests

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#28]
For a start the integration tests would assume (and test for) a working Tekton cluster. The user/developer would make sure that the `kubectl` and `tkn` environment is configured and the Python script would rely on shell commands to apply the Tekton YAML files, start Tekton pipelines, check pipeline run output and remove the resources created in the course of the integration tests.

In the future this setup should be improved to use containers for Tekton and appropriate Python libraries to execute the tests.

Conceptually, each individual integration test would take one of the `Golden` YAML files from the `sdk/python/tests/compiler/testdata` folder and do:
- `kubectl apply -f some.yaml`
- `tkn pipeline start some-pipeline`
- `tkn pipeline logs parallel-pipeline --last   > some-pipeline-run.log`
- some smart diff of `some-pipeline-run.log` and `some-pipeline-run.expected.log` which was previously captured

**Comment by kalakandi** [comment]
I'm on it

**Comment by ckadner** [comment]
Hi @kalakandi, are you still working in the integration tests?

**Comment by kalakandi** [comment]
Hi @ckadner, yes was reading the kubernetes docs as I m a little new to it, i need a little guidance TBH

**Comment by ckadner** [comment]
> ... was reading the kubernetes docs as I m a little new to it, i need a little guidance TBH

@kalakandi -- I may have mislabeled this issue. It is not a good first issue for people who are unfamiliar with this Kubernetes. I intended to mark this as a good issue for people who are new to this project, but it requires solid knowledge/experience with Kubernetes, Kubeflow, Tekton and Python. There may be better issues to start with than this one.

**Comment by kalakandi** [comment]
Ok, then I'll work on another issue. Please unassign
