### ISSUE TITLE
remove KUBECONFIG dependency for test

### ISSUE THREAD

**Issue by adrian555** [kubeflow/kfp-tekton#284]
/kind bug

**What steps did you take and what happened:**
Login to an OpenShift cluster with token `oc login --token=xxx --server=https://xxx:6443`, no KUBECONFIG env is set nor required for accessing the cluster. Run `make test` will fail.

**What did you expect to happen:**
`make test` should succeed.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`): 3.6
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`): 1.16
* OS (e.g. from `/etc/os-release`): MacOS

**Comment by ckadner** [comment]
The `KUBECONFIG` check was added as an early abort mechanism to report a concise usage error message as opposed to exposing the user to less clear error messages when the E2E tests are attempting to access the cluster via the `kubectl` or `tkn` CLI later on. Using the `KUBECONFIG` environment variable is concise way to pass the cluster context to downward `shell` or `python` processes, i.e. in runtime configuration of IDEs.

@adrian555 -- Do you have a suggestion for a platform independent environment variable we can rely on?

**Comment by adrian555** [comment]
@ckadner a couple of things:
* you don't need the KUBECONFIG to run `kubectl` in the python test code
* instead of running `kubectl` commands, how about `https://github.com/kubernetes-client/python`? (aka `pip install kubernetes` then 
```
from kubernetes import client, config
k8s_client = config.new_client_from_config()
```)?

**Comment by ckadner** [comment]
>     * you don't need the KUBECONFIG to run `kubectl` in the python test code if you already login to the cluster

I use environment variables in order to run test configurations targeting various clusters where I do not have a logon shell to run `oc` commands prior to test execution. Same for containerized environments. 

>     * instead of running `kubectl` commands, how about `https://github.com/kubernetes-client/python`? (aka `pip install kubernetes` then

The Python client for is not as intuitive and straight-forward as the `kubectl` CLI both for the programming of things as simple as a `kubectl apply -f ..` and for the error messages returned. I chose to rely on `kubectl` instead since that any K8s user would be used to to running the commands and can easily copy and paste failed commands to a shell and verify the output or debug errors.

**Comment by adrian555** [comment]
cc @Tomcli since he asked to open this issue. As for how or whether to fix this, up to the team to discuss. Thanks.

**Comment by Tomcli** [comment]
@ckadner i think the issue we have is the new ibm cloud CLI from 3 months ago moved away from KUBECONFIG and put all the k8s credentials under `$HOME/.kube/config`. And for minikube, fyre, and other cloud platform they are doing similar way.

**Comment by Tomcli** [comment]
maybe we should based it on `kubectl config current-context` and see does they actually have access to a real k8s cluster.

**Comment by ckadner** [comment]
I want to make sure the `make e2e_test` target as well as the `sdk/python/tests/compiler/compiler_tests_e2e.py` work from a shell environment as well as in IDE runtime configurations or in container based environments. Environment variables work in all of those environments. If we want to support both OpenShift and standard Kubernetes target clusters, we may need to add some additional code for that. Ideally as little as possible.

For the `Makefile` could we do something like this?

```Bash
KUBECONFIG="${KUBECONFIG:-~/.kube/config}"
```

**Comment by Tomcli** [comment]
> I want to make sure the `make e2e_test` target as well as the `sdk/python/tests/compiler/compiler_tests_e2e.py` work from a shell environment as well as in IDE runtime configurations or in container based environments. Environment variables work in all of those environments. If we want to support both OpenShift and standard Kubernetes target clusters, we may need to add some additional code for that. Ideally as little as possible.
> 
> For the `Makefile` could we do something like this?
> 
> ```shell
> KUBECONFIG="${KUBECONFIG:-~/.kube/config}"
> ```

~/.kube/config can be point to an invalid endpoint. Can we run a simple checking with `kubectl config current-context` before assigning to KUBECONFIG?

**Comment by ckadner** [comment]
I opened a PR #291 to remove the hard dependency on `KUBECONFIG` but I left it as an option with a warning to alert the user that the targeted cluster might not be the expected one.
