### ISSUE TITLE
Update end to end tests to also test API and client.

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#301]
/kind feature

**Description:**
Currently, our end to end tests are only testing with pure tekton features. We need to extend our testing to also cover the api and the client. 

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
https://github.com/kubeflow/kfp-tekton/tree/master/samples/kfp-user-guide#3-upload-pipelines-using-the-kfp-bash-command-line-tool
should be a good starting point to test pipelines using bash commands.

**Comment by Tomcli** [comment]
/assign @ckadner 
Will provide example soon

**Comment by Tomcli** [comment]
run pipeline
```
kfp run submit -r test -e Default -f echo_pipeline.yaml
```
stdout
```
Run b1724e85-51e3-4522-8425-6096ff076601 is submitted
+--------------------------------------+--------+----------+---------------------------+
| run id                               | name   | status   | created at                |
+======================================+========+==========+===========================+
| b1724e85-51e3-4522-8425-6096ff076601 | test   |          | 2020-09-09T19:10:19+00:00 |
+--------------------------------------+--------+----------+---------------------------+
```

view pipeline (need to grep run id from previous)
```
kfp run get b1724e85-51e3-4522-8425-6096ff076601
```
stdout
```
+--------------------------------------+--------+-----------+---------------------------+
| run id                               | name   | status    | created at                |
+======================================+========+===========+===========================+
| b1724e85-51e3-4522-8425-6096ff076601 | test   | Succeeded | 2020-09-09T19:10:19+00:00 |
+--------------------------------------+--------+-----------+---------------------------+
```

@ckadner There not much support for the kfp cli, so if you think using Python SDK is easier then I will recommend that instead.

**Comment by ckadner** [comment]
Thank you @Tomcli -- I will use the Python client (`kfp_tekton.TektonClient`) to submit the `PipelineRun`s and keep using the `tkn` CLI to get the run status and logs

**Comment by Tomcli** [comment]
Just be aware the run id for kfp is different from the pipelinerun name, those mapping are only available under the mysql database just like argo.

**Comment by ckadner** [comment]
I got it this way:

```Python
run = kfp.Client().get_run(run_id)
workflow_manifest = json.loads(run.pipeline_runtime.workflow_manifest)
tkn_pipelinerun_name = workflow_manifest['metadata']['name']
```

**Comment by Tomcli** [comment]
Ah I see, you actually pull from the workflow manifest. Yes then this should be correct.
