### ISSUE TITLE
Server API does not accept Tekton YAML with dependency specified by `after` on condition node

### ISSUE THREAD

**Issue by rafalbigaj** [kubeflow/kfp-tekton#310]
/kind bug

**What steps did you take and what happened:**

The successfully compiled tekton YAML:
[train_and_validate_in_notebook_pipeline.py.tar.gz](https://github.com/kubeflow/kfp-tekton/files/5232905/train_and_validate_in_notebook_pipeline.py.tar.gz)

from source:
https://github.ibm.com/AILifecycle/ai-kubeflow-pipelines/blob/new-components/pipelines/train_and_validate_in_notebook_pipeline.py#L135

fails, when trying to create a run with error:
```
 InternalServerError: Failed to create a workflow for (train-the-model-and-evaluate-in-notebook-f3ee6):
 admission webhook \"validation.webhook.pipeline.tekton.dev\" denied the request: validation failed: invalid value:
 couldn't add link between run-notebook and condition-positive-condition-1:
 task run-notebook depends on condition-positive-condition-1 but condition-positive-condition-1 wasn't present in Pipeline: 
 spec.tasks
```

**What did you expect to happen:**

The same DSL code compiled to Argo YAML can be run without any issues.

**Additional information:**
N/A

**Environment:**

* Python Version (use `python --version`): 3.7
* SDK Version: 0.3.0
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
Thanks @rafalbigaj, we will take a look and see can we do some workaround with the alpha conditional API. If not, we will prompt an error in the SDK for now and try to address it in the beta conditional API during the next major release.

**Comment by Tomcli** [comment]
FYI @ckadner @drewbutlerbb4 
Since the alpha tekton condition is not a regular task (also it's an older api), it's not possible to refer it as a dependencies such as .after(conditions) or condition.results. So let's see is there any workaround we can do on the compiler side.

**Comment by Tomcli** [comment]
This feature is supported in the master branch now.
