### ISSUE TITLE
Add example for watson openscale

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#324]
/kind feature

**Description:**
Update the watson openscale example to use the new analytics-engine service to replace spark.
https://github.com/kubeflow/pipelines/tree/master/samples/contrib/ibm-samples/openscale

https://cloud.ibm.com/catalog/services/analytics-engine
https://cloud.ibm.com/catalog/services/watson-openscale
https://cloud.ibm.com/catalog/services/machine-learning

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by fenglixa** [comment]
OK, let me handle it.
