### ISSUE TITLE
Sanitizing Kubernetes resources into strings

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#332]
/kind feature

**Description:**
Some Kubernetes resources such as `V1EnvVar` for container environment variables only accept string, so we need to let the SDK to sanitize these variables into proper strings before dumping it to Tekton YAML.

The Kubernetes API docs defines what types are supported under the pod spec.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/

/good-first-issue

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
Here is an example where it could fail when running
```
from kubernetes.client.models import V1EnvVar
from kfp import dsl

def echo_op():
    return dsl.ContainerOp(
        name='echo',
        image='busybox',
        command=['sh', '-c'],
        arguments=['echo "Got scheduled"']
    ).container.add_env_variable(V1EnvVar(name='PORT', value=80))

@dsl.pipeline(
    name='echo',
    description='echo pipeline'
)
def echo_pipeline(
):
    echo = echo_op()

from kfp_tekton.compiler import TektonCompiler
TektonCompiler().compile(echo_pipeline, 'echo_pipeline.yaml')
```

**Comment by Tomcli** [comment]
and we need to update the compiler to convert `V1EnvVar` values into string

**Comment by jizg** [comment]
I'd like to have a try. I will firstly to setup the development environment and reproduce this problem.

**Comment by Tomcli** [comment]
thanks @jizg, here is the sdk setup https://github.com/kubeflow/kfp-tekton/tree/master/sdk

**Comment by jizg** [comment]
@Tomcli I did some investigation in KF pipeline and kfp-tekton codes. I found this `import` definition in pipeline dsl SDK. Are these resources the kubernetes resources that you think we should sanitize?

https://github.com/kubeflow/pipelines/blob/2676b56151ba57f17fd43c5e0734297632724785/sdk/python/kfp/dsl/_container_op.py#L20-L24

```python
from kubernetes.client.models import (
    V1Container, V1EnvVar, V1EnvFromSource, V1SecurityContext, V1Probe,
    V1ResourceRequirements, V1VolumeDevice, V1VolumeMount, V1ContainerPort,
    V1Lifecycle, V1Volume
)
```
And I also checked the kubernetes specification of [V1ContainerPort](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core), and found that `containerPort` and `hostPort` is defined as **ingeter**. I compiled a test pipeline yaml to use string '80' as `containerPort`, and got the following error when creating an pipeline by this yaml.

>Failed to parse the parameter.: error unmarshaling JSON: json: cannot unmarshal string into Go struct field ContainerPort.spec.pipelineSpec.tasks.taskSpec.steps.ports.containerPort of type int32

So I think it is also possible to sanitize string into integer.

Could you help check whether my understanding is OK? Thanks

**Comment by Tomcli** [comment]
Thanks @jizg, yes that's correct. Right now our compiler doesn't sanitize these string/int types so there will be errors when running these pipelines. It will be great if you can sanitize these variables (like you pointed out containerPort should be int32). If any of these variables cannot be sanitized, prompt an error to the users telling that they need to input the correct type.

**Comment by jizg** [comment]
@Tomcli Thanks for your reply. The feature requirement is clear for me now. I think I can work on this. 
And I also found you raised the following issue, doese it make sense to create a common sanitization class or module to handle them together?

https://github.com/kubeflow/kfp-tekton/issues/342

**Comment by Tomcli** [comment]
Yes. For your initial PR, you can put your helper functions/modules under this file. 
https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/_k8s_helper.py

For #342, I want to offload some functions from big data passing since it's growing too big, and hence you are seeing some issues popping up for artifact passing. You can address this in a follow-up PR if you're interested.
