### ISSUE TITLE
Pipeline compiled by python SDK 0.3.0 installed by pip failed when running

### ISSUE THREAD

**Issue by jizg** [kubeflow/kfp-tekton#339]
/kind bug

**What steps did you take and what happened:**

I created a pipeline to test passing file artifacts between tasks. When the pipeline is compiled by SDK installed from pip, the execution failed. But if I install SDK compiled from the lastest master branch, it worked without problem.

**What did you expect to happen:**

pip installed SDK should work without  problem.

**Additional information:**

[pipeline_yaml.zip](https://github.com/kubeflow/kfp-tekton/files/5420417/pipeline_yaml.zip)

pipeline yaml diff, upper is the one compiled by pip SDK.
```
<       "$(results.output-text.path)"]]}'
---
>       "$(workspaces.repeat-line.path)/repeat-line-output_text"]]}'
84,85c84,90
<     persistentVolumeClaim:
<       claimName: test-pipeline
---
>     volumeClaimTemplate:
>       spec:
>         accessModes:
>         - ReadWriteMany
>         resources:
>           requests:
>             storage: 2Gi
```

code to generate pipeline:
```python
def test_pipeline():
    @func_to_container_op
    def repeat_line(line: str, output_text_path: OutputPath(str), count: int = 10):
        '''Repeat the line specified number of times'''
        with open(output_text_path, 'w') as writer:
            for i in range(count):
                writer.write(line + '\n')


    # Reading big data
    @func_to_container_op
    def print_text(text_path: InputPath()): # The "text" input is untyped so that any data can be printed
        '''Print text'''
        with open(text_path, 'r') as reader:
            for line in reader:
                print(line, end = '')

    repeat_lines_task = repeat_line(line='Hello', count=500)
    print_text(repeat_lines_task.output) # Don't forget .output !

TektonCompiler().compile(test_pipeline, 'print_repeating_lines_pipeline.yaml')
```

**Environment:**

* Python Version (use `python --version`): Python 3.7.8
* SDK Version: 0.3.0
* Tekton Version (use `tkn version`): not installed
* Kubernetes Version (use `kubectl version`): 1.16.15
* OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by Tomcli** [comment]
yes there's a bug with the big data passing, I fixed few weeks ago and it will in our 0.4 release.
