### ISSUE TITLE
Disabling pipeline timeout doesn't work

### ISSUE THREAD

**Issue by jfigura** [kubeflow/kfp-tekton#352]
/kind bug

**What steps did you take and what happened:**
Disabling pipeline timeout should be possible by setting the timeout to 0. However, setting the timeout to 0 currently doesn't create the timeout field in Tekton YAML and therefore the default (60m) is used.

**What did you expect to happen:**
`dsl.get_pipeline_conf().set_timeout(0)` should be supported so that the generated Tekton YAML explicitly contains `timeout: 0`.

**Additional information:**
I believe the issue comes from https://github.com/kubeflow/kfp-tekton/blob/033161415d7ed52aeb3660b406368a91485d3b28/sdk/python/kfp_tekton/compiler/compiler.py#L175 which should be checking for `None` instead.

**Comment by fenglixa** [comment]
Thanks for your report, we can disable timeout if set timeout as zero, but it's better compare with kubeflow pipeline to keep the behavior consistant.

**Comment by jfigura** [comment]
@fenglixa in Argo Kubeflow pipelines, there's no timeout by default. Using `dsl.get_pipeline_conf().set_timeout(0)` produces the exact same YAML as default, i.e. no timeout. Using a positive number, e.g. `dsl.get_pipeline_conf().set_timeout(1)` sets `activeDeadlineSeconds` to the given value. So setting timeout to 0 in tekton in case of `set_timeout(0)` would be consistent. It's also claimed by https://github.com/kubeflow/kfp-tekton/pull/68, but doesn't actually work that way.

**Comment by Tomcli** [comment]
In Kubeflow pipeline DSL, the default timeout value is 0, so setting the timeout to 0 doesn't change the default value when passed to our compiler. I can make everything is not timeout by default to align with Argo's behavior.
