### ISSUE TITLE
Upload version 0.4.0 of the SDK to PyPI 

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#362]
Preview release on `test.PyPI.org`:
https://test.pypi.org/project/kfp-tekton/0.4.0rc1/

Related: #339

/cc @Tomcli @animeshsingh

/assign

**Comment by ckadner** [comment]
Waiting on PR #361 to be reviewed before pushing the real PyPI release

**Comment by ckadner** [comment]
https://test.pypi.org/project/kfp-tekton/0.4.0rc2/

**Comment by Tomcli** [comment]
thanks @ckadner, it looks good to me.

**Comment by ckadner** [comment]
The new release `0.4.0` is now on PyPI! 🎉 

https://pypi.org/project/kfp-tekton/0.4.0/

@animeshsingh @Tomcli
