### ISSUE TITLE
Fresh standalone install causes "error no matches for kind Application" 

### ISSUE THREAD

**Issue by drewbutlerbb4** [kubeflow/kfp-tekton#375]
/kind bug

**What steps did you take and what happened:**
Fresh install of tekton pipelines and then standalone kfp-tekton
```kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.16.3/release.yaml```
```kubectl apply -f install/v0.4.0/kfp-tekton.yaml```

Results (during kfp-tekton install):
```
...
condition.tekton.dev/super-condition created
persistentvolumeclaim/minio-pvc created
persistentvolumeclaim/mysql-pv-claim created
error: unable to recognize "install/v0.4.0/kfp-tekton.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"
```

This is fixed by running the kfp-tekton install again. 
It seems to be the same issue as one they are having in: https://github.com/kubeflow/kubeflow/issues/2380

Is this fixable or should we add this to the troubleshooting doc?

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
The crd should be created at the beginning of the kfp-tekton.yaml. Can you make sure the kubectl version matches with the k8s server version, then delete and rerun the `kubectl apply` command?

**Comment by fenglixa** [comment]
encounter this issue today:
```
persistentvolumeclaim/mysql-pv-claim unchanged
error: unable to recognize "install/v0.4.0/kfp-tekton.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"
```
kubectl version is matched:
```
root@rentz1:/opt/kube/kfp-tekton# kc version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

workaround by apply again

**Comment by Tomcli** [comment]
OK, it looks like there's some race condition since the crd takes few second to register to the k8s api. We can follow the Knative approach to deploy the crd first, then deploy the cr few seconds after.
