### ISSUE TITLE
Things to consider for the KFP IR design

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#382]
/kind question

**Question:**
Tekton and Argo go clients use different go dependencies. As we are still seeking new features from Tekton, we would like to use the latest Tekton client if possible which uses very new version of client-go library. As the result, we cannot put the Tekton and Argo into a single microservice/package because they always have version conflicts with all the k8s related packages. Considering all the future pipeline engines may have their own set of golang dependencies, it would be better if each pipeline engine can wrap into an independent service. This way KFP can pass the IR to any pipeline engine client using API without worrying any golang dependency. This is similar to how KFServing handle different machine learning frameworks by having each framework to run on its own container.

**Comment by Tomcli** [comment]
![Uploading Screen Shot 2020-12-02 at 5.58.14 PM.png…]()

**Comment by Tomcli** [comment]
<img width="994" alt="Screen Shot 2020-11-24 at 5 59 00 PM" src="https://user-images.githubusercontent.com/10889249/100953733-ffd1ae00-34c7-11eb-8eb9-3ab966c3b0f2.png">

**Comment by Tomcli** [comment]
<img width="1163" alt="Screen Shot 2020-12-02 at 5 59 24 PM" src="https://user-images.githubusercontent.com/10889249/100953783-1e37a980-34c8-11eb-935c-d9e45dc3d72b.png">

**Comment by tonanhngo** [comment]
It seems natural to deploy the Tekton or Argo backend compiler in separate microservices.  Is there a scenario where it would be advantageous to package them together?

**Comment by Tomcli** [comment]
Putting argo and tekton go client in the kfp backend microservice can reduce the HTTP/GRPC overheads for deploying/getting the pipeline engine CRDs. The trade off is all the packages have to use the same client-go version. In this case it's blocking us because these packages are hosted between 3 different communities.
