### ISSUE TITLE
Running parallel_join on openshift 4.3.1

### ISSUE THREAD

**Issue by kevinyu98** [kubeflow/kfp-tekton#39]
Openshift 4.3.1 with openshift pipeline 

then run parallel_join samples.

`./oc apply -f https://raw.githubusercontent.com/kubeflow/kfp-tekton/ab5d43331a53600f3baecd1969ca6f3a101350fc/sdk/python/tests/compiler/testdata/parallel_join.yaml
`

`tkn pipeline start parallel-pipeline`

Here is the log

`(.venv) (base) Qianyangs-MBP:kevin-openshift-v4-tekton qianyangyu$ ./oc apply -f https://raw.githubusercontent.com/kubeflow/kfp-tekton/ab5d43331a53600f3baecd1969ca6f3a101350fc/sdk/python/tests/compiler/testdata/parallel_join.yaml
task.tekton.dev/gcs-download created
task.tekton.dev/gcs-download-2 created
task.tekton.dev/echo created
pipeline.tekton.dev/parallel-pipeline created
(.venv) (base) Qianyangs-MBP:kevin-openshift-v4-tekton qianyangyu$ tkn pipeline start parallel-pipeline
? Value for param `url1` of type `string`? (Default is `gs://ml-pipeline-playground/shakespeare1.txt`) gs://ml-pipeline-playground/shakespeare1.txt
? Value for param `url2` of type `string`? (Default is `gs://ml-pipeline-playground/shakespeare2.txt`) gs://ml-pipeline-playground/shakespeare2.txt
Pipelinerun started: parallel-pipeline-run-k7chw

In order to track the pipelinerun progress run:
tkn pipelinerun logs parallel-pipeline-run-k7chw -f -n default
(.venv) (base) Qianyangs-MBP:kevin-openshift-v4-tekton qianyangyu$ tkn pipelinerun logs parallel-pipeline-run-k7chw -f -n default
[gcs-download : gcs-download] {"level":"info","ts":1584642628.819261,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
[gcs-download : gcs-download] With which he yoketh your rebellious necks Razeth your cities and subverts your towns And in a moment makes them desolate

[echo : echo] {"level":"info","ts":1584642648.9410698,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
[echo : echo] Text 1: gs://ml-pipeline-playground/shakespeare1.txt
[echo : echo] Text 2: gs://ml-pipeline-playground/shakespeare2.txt

[gcs-download-2 : gcs-download-2] {"level":"info","ts":1584642629.569524,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
[gcs-download-2 : gcs-download-2] I find thou art no less than fame hath bruited And more than may be gatherd by thy shape Let my presumption not provoke thy wrath

`

**Comment by ckadner** [comment]
Hi @kevinyu98 thanks for testing this on **OpenShift 4.3**

The output looks good. Why is this a `Bug`?

**Comment by kevinyu98** [comment]
this seems run successfully. I didn't put it as bug, somehow when I create issue, it automatically tag it.
