### ISSUE TITLE
Nested conditions are wrongly getting unnested

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#397]
/kind bug

**What steps did you take and what happened:**
A modified flip coin example in three variants to compare the results:

```python
def flipcoin1(forced_result1: str = 'heads', forced_result2: str = 'heads'):
    flip1 = FlipCoinOp('flip1', str(forced_result1))
    flip2 = FlipCoinOp('flip2', str(forced_result2))

    with dsl.Condition(flip1.output == 'heads'):
        PrintOp('print', "{} {}".format(flip1.output, flip2.output))
```
```python
def flipcoin2(forced_result1: str = 'heads', forced_result2: str = 'heads'):
    flip1 = FlipCoinOp('flip1', str(forced_result1))
    flip2 = FlipCoinOp('flip2', str(forced_result2))

    with dsl.Condition(flip1.output == 'heads'):
        with dsl.Condition(flip2.output == 'heads'):
            PrintOp('print', "{} {}".format(flip1.output, flip2.output))
```
```python
def flipcoin3(forced_result1: str = 'heads', forced_result2: str = 'heads'):
    flip1 = FlipCoinOp('flip1', str(forced_result1))
    flip2 = FlipCoinOp('flip2', str(forced_result2))

    with dsl.Condition(flip1.output == 'heads'):
        PrintOp('print-debug', "debug!")
        with dsl.Condition(flip2.output == 'heads'):
            PrintOp('print', "{} {}".format(flip1.output, flip2.output))
```

For Argo target, it looks as expected:
```condition1.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1 (deps: flip1, flip2), when flip1.output == "heads"
      |- print

condition2.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1 (deps: flip1, flip2), when flip1.output == "heads"
      |- condition-2, when flip2.output == "heads"
         |- print

condition3.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1 (deps: flip1, flip2), when flip1.output == "heads"
      |- debug-print
      |- condition-2, when flip2.output == "heads"
         |- print
```

For Tekton backend, though, the following is happening:
```
condition1.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
      |- print, when condition-1.status in "true"

condition2.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
   |- condition-2: flip2.output == "heads"
      |- print, when condition-2.status in "true"

condition3.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
      |- print-debug, when condition-1.status in "true"
   |- condition-2: flip2.output == "heads"
      |- print, when condition-2.status in "true"
```

**What did you expect to happen:**

condition1.py looks fine to me

condition2.py looks like condition-1 is simply ignored instead of making a chain of dependency. I'd expect it to be sth like (it should be possible, now that the conditions' templates aren't limited to a single `super-condition` resource):
```
condition2.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
      |- condition-2: flip2.output == "heads", when condition-1.status in "true"
         |- print, when condition-2.status in "true"
```

condition3.py looks like condition-1 is only applied to ContainerOps that are directly under it with no other group in-between, thus making the two conditions independent of each other. I'd expect it looked like that instead:
```
condition3.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
      |- print-debug, when condition-1.status is "true"
      |- condition-2: flip2.output == "heads", when condition-1.status in "true"
         |- print, when condition-2.status in "true"
```

Both condition2.py and condition3.py look like conditions are simply factored out of any nesting:

```python
def flipcoin2(forced_result1: str = 'heads', forced_result2: str = 'heads'):
    flip1 = FlipCoinOp('flip1', str(forced_result1))
    flip2 = FlipCoinOp('flip2', str(forced_result2))

    with dsl.Condition(flip1.output == 'heads'):
        pass
    with dsl.Condition(flip2.output == 'heads'):
        PrintOp('print', "{} {}".format(flip1.output, flip2.output))
```

```python
def flipcoin3(forced_result1: str = 'heads', forced_result2: str = 'heads'):
    flip1 = FlipCoinOp('flip1', str(forced_result1))
    flip2 = FlipCoinOp('flip2', str(forced_result2))

    with dsl.Condition(flip1.output == 'heads'):
        PrintOp('print-debug', "debug!")
    with dsl.Condition(flip2.output == 'heads'):
        PrintOp('print', "{} {}".format(flip1.output, flip2.output))
```

**Additional information:**
It looks like only tasks get the `when` at all, as I can only see it in [looping over `task_refs` directly in `_create_pipeline_workflow`](https://github.com/kubeflow/kfp-tekton/blob/66f33514d8217ed8c36b6af09f94919b5c2b7851/sdk/python/kfp_tekton/compiler/compiler.py#L414-L421):

```python
    # add task dependencies and add condition refs to the task ref that depends on the condition
    op_name_to_parent_groups = self._get_groups_for_ops(pipeline.groups[0])
    for task in task_refs:
      op = pipeline.ops.get(task['name'])
      parent_group = op_name_to_parent_groups.get(task['name'], [])
      if parent_group:
        if condition_refs.get(parent_group[-2], []):
          task['when'] = condition_refs.get(op_name_to_parent_groups[task['name']][-2], [])
```

**Environment:**

* Python Version (use `python --version`): 3.9.0 (although it should be irrelevant)
* SDK Version: 0.5.0
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
Thanks @Udiknedormin, I just came back from the holidays. I will try to address it in our SDK.

**Comment by Tomcli** [comment]
Since Tekton doesn't provide a way to create nested component (like Argo DAG or sub-pipeline), I updated it to check all the chained conditions together to simulate the nested condition edge cases above. Since the condition only need to compute once so it doesn't impact the performance.

Ideally it should be done in a "nested pipeline/graph" like Argo, but we had some push back on the nested pipeline when we brought it up in the early loop design. The datastage team is creating a new custom task controller that can handle sub-pipelineruns, so hopefully we can apply it to all the argo nested component as well.

**Comment by Tomcli** [comment]
The new fixes should update the above examples as:
```
condition1.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
      |- print, when condition-1.status in "true"

condition2.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
   |- condition-2: flip2.output == "heads"
   |- print, when condition-1 and condition-2.status in "true"

condition3.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
   |- print-debug, when condition-1.status in "true"
   |- condition-2: flip2.output == "heads"
   |- print, when condition-1 and condition-2.status in "true"
```

**Comment by Udiknedormin** [comment]
@Tomcli Hmm. I can only see one problem with that solution, it is visible in the third example.

Your solution:

```
condition3.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
   |- condition-2: flip2.output == "heads"
   |- print-debug, when condition-1.status in "true"
   |- print, when condition-1 and condition-2.status in "true"
```

I.e. even if the condition-1 is false, condition-2 is still evaluated (and therefore is created a task). No short-circuiting, basically. It may also affect the control flow graphs in the UI.

Is there any technical issue with making one condition depend on another (i.e. adding a `when` to a condition)? It seems to me that would solve all of the above issues and shouldn't be all that complicated (it just requires to pass the immediate parent conditions' name to child condition, pretty much how we already do for tasks).

Your solution, however, looks promising in case of "simple conditions" that we were analysing, i.e. comparisons that actually can be done via Tekton's `when` directly, without creating a new task (a typical example being: "when task A's output err is an empty string").

**Comment by Tomcli** [comment]
So we agreed with your approach to make the condition depend on its parent since all conditions are evaluated in a regular Tekton task after we moved to whenExpression. Here is the new condition3 example
```
condition3.py
|- flip-coin-example-pipeline
   |- flip1
   |- flip2
   |- condition-1: flip1.output == "heads"
   |- print-debug, when condition-1.status in "true"
   |- condition-2: flip2.output == "heads", when condition-1.status in "true"
   |- print, when condition-2.status in "true"
```

**Comment by Udiknedormin** [comment]
Great, that is exactly how I imagined it to be working, seems to cover all of the use-cases. Thank you!
