### ISSUE TITLE
Introduce TTL for Pipelinerun prune

### ISSUE THREAD

**Issue by vincent-pli** [kubeflow/kfp-tekton#398]
/kind feature

**Description:**
Seems we do not consider `pipelinerun` clean up, I guess the feature is necessary for produce level.
I saw there is `kfp.dsl.PipelineConf.set_ttl_seconds_after_finished` but it's for Argo, it's based on Argo's `ttlStrategy` and `tekton` has no such feature.

So I think we could introduce new label, maybe `tekton.dev/ttl` and set the label to `pipelinerun` in `compiler`. 
Then introduce a prune components(a cron job maybe) to purge old `pipelinerun` leverage the value of the `tekton.dev/ttl`.

Is that make sense?
@animeshsingh @Tomcli @fenglixa 

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
KFP already has a simple TTL that removes the pipelineruns that are more than 1 day old. You can change this default value in the manifests at https://github.com/kubeflow/kfp-tekton/blob/master/manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml#L22-L23

Here is the current TTL implementation we used in kfp https://github.com/kubeflow/kfp-tekton/blob/master/backend/src/agent/persistence/worker/workflow_saver.go

**Comment by vincent-pli** [comment]
Thanks @Tomcli 
but seems it's for workflow persistence(correct me), not for `pipelinerun`(workflow) clean up.

**Comment by Tomcli** [comment]
> Thanks @Tomcli
> but seems it's for workflow persistence(correct me), not for `pipelinerun`(workflow) clean up.

workflow is what kubeflow call their pipelines (the name comes from Argo), but we have updated the client to delete the pipelinerun instead.

The persistent agent will add the TTL period. Once it's expired, the agent will make sure the data is persisted and remove the pipelinerun crd.

**Comment by Tomcli** [comment]
you can try to change the TTL to 1 minutes and verify at your end.

**Comment by vincent-pli** [comment]
Great, I saw the code:
https://github.com/kubeflow/kfp-tekton/blob/dc6014ded8fab2f0628c7791887e339aa5369518/backend/src/apiserver/resource/resource_manager.go#L804
