### ISSUE TITLE
clarify the anySequencer failure case

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#409]
> One question to @jinchihe @fenglixa, for the anySequencer, in the event that all of the dependencies of the anySequencer fail should we mark the task that depends on the anySequencer as skipped? This way it would show up in the runtime execution graph, whereas currently the last task in this scenario does not display as shown below ([the example pipeline used](https://github.com/drewbutlerbb4/kfp-tekton/blob/sequencer-bug-example/sdk/python/tests/compiler/testdata/any_sequencer_bug.yaml)).
> 
> <img alt="Screen Shot 2021-01-06 at 2 24 06 PM" width="1073" src="https://user-images.githubusercontent.com/32145094/103826021-e1ad1f80-502a-11eb-9cb7-8a5c05da2cf6.png">

@jinchihe @fenglixa I'm not sure how anySequencer suppose to behave in datastage for the failure scenario, but currently the `anySequencer` container will keep running until it sees a succeeded task or sees no events for 10 minutes. Should we add some way to fail fast if all the tasks are failed?

_Originally posted by @Tomcli in https://github.com/kubeflow/kfp-tekton/issues/408#issuecomment-756335558_

**Comment by fenglixa** [comment]
Thank you @Tomcli, for your report this.  Personally, I think this is an issue in `any sequencer` need to be addressed. @jinchihe, how do you think?

**Comment by jinchihe** [comment]
Seems that's a bug, I will take a look. Good catch! Thanks @Tomcli 

/assign
