### ISSUE TITLE
migrate to kfp 1.3.0

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#410]
/kind feature

**Description:**
https://github.com/kubeflow/pipelines/releases/tag/1.3.0

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
/assign @ckadner 
let me know if you need any help from me.

**Comment by ckadner** [comment]
@Tomcli, @animeshsingh -- in order to keep additional merges/rebases to a minimum, I propose to merge the large PRs currently in progress, like #395, before I start to create a PR for the KFP upgrade
