### ISSUE TITLE
update Katib examples to use v1beta1 api

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#411]
/kind feature

**Description:**
Katib introduced the new v1beta1 api component and merged in mid December. We need to upgrade our katib examples if we want to use the latest API from katib (need kubeflow 1.2+)

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ScrapCodes** [comment]
@Tomcli Can we resolve this as well?
