### ISSUE TITLE
Investigate how to put custom task spec into pipelinerun

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#416]
/kind feature

**Description:**
Related #412 

Currently, custom task doesn't support pipeline.taskSpec, so we cannot generate the loop pipeline using just one single pipelinerun CR. If we are going to take custom task as a separate resource, we need to build a custom task registry that's just for a particular custom task type (like pipelineloop). 

So ideally we want to make Tekton's pipeline.taskSpec to support custom task and it also can help minimize the numbers of CR we create.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by fenglixa** [comment]
Thanks @Tomcli 
I investigated it yet, that custom-task doesn't support pipeline.taskSpec currently.

A potential solution is: create a resourceOps task as the first task in the pipelinerun CR. This solution could ennsure that's a single pipelinerun CR.

How do you think?

**Comment by Tomcli** [comment]
So based on the Tekton community comment, they will take some time to get the user feedbacks before adding the `taskSpec` support. So we can use resourceOps to deploy our custom task resource if that works for the datastage team.

**Comment by fenglixa** [comment]
Fet the feedback from tekton  https://github.com/tektoncd/pipeline/issues/3682, they will support taskSpec defining for custom task, so we don't need to rush to support  it via resourceOps for now.

**Comment by Tomcli** [comment]
@fenglixa the resourceOps option probably won't work because the pipeline will not start until all the task references is present. I think our best option is to use the taskSpec if possible. 

I think the Tekton community don't have a strong objection. If the community is not picking this up, we can start changing the Tekton reconciler and create do some experiments to provide feedbacks.
https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L356-L366

**Comment by fenglixa** [comment]
@Tomcli the pipeline won't block if the task references are not present, that mean resourceOps option is working to us from functionally. The first task will be executed, the pipeline will be failed while the reference task starting to run but didn't find it.
