### ISSUE TITLE
The copy-artifacts step failed due to no tar command

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfp-tekton#427]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
[root@symtest11 ~]# kubectl logs -n kubeflow job-activity-22957-job-activity-mkfqj-pod-j44ck -c step-copy-artifacts
Added `storage` successfully.
/tekton/scripts/script-2-7sn72: line 3: tar: command not found
mc: <ERROR> Unable to validate source `run_id.tgz`.
/tekton/scripts/script-2-7sn72: line 3: tar: command not found
mc: <ERROR> Unable to validate source `run_state.tgz`.
[root@symtest11 ~]#
```

**What did you expect to happen:**
The artifacts should be copied successfully.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`): 3.8
* SDK Version:  0.5
* Tekton Version (use `tkn version`): 
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
@jinchihe you need to update the kfp-tekton config
https://github.com/kubeflow/kfp-tekton/blob/master/manifests/kustomize/env/platform-agnostic/kfp-pipeline-config.yaml#L9

This is cherrypicked into 1.2 branch few weeks ago.

**Comment by jinchihe** [comment]
@Tomcli Oh, thank you very much to point out this!

**Comment by jinchihe** [comment]
That's OK now after updated the image. Thanks.
/close
