### ISSUE TITLE
Update UI to support custom task and pipeline run status for tekton 0.19+

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#429]
/kind feature

**Description:**
Tekton 0.19+ introduced new breaking syntax in its pipelinerun.status. So we need to update the UI after the #428 PR.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by drewbutlerbb4** [comment]
Thanks @Tomcli, I'll start working on this

**Comment by Tomcli** [comment]
@drewbutlerbb4 it only happens on tekton 0.19+. and you can recreate this with the latest 0.6 standalone install https://github.com/kubeflow/kfp-tekton/blob/master/guides/kfp_tekton_install.md#standalone-kubeflow-pipelines-with-tekton-backend-deployment
