### ISSUE TITLE
UI enhancement to support loops feature for kfp-tekton

### ISSUE THREAD

**Issue by fenglixa** [kubeflow/kfp-tekton#431]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]

This issue is trace for UI enhancement to support loops feature for kfp-tekton

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]
/assign

**Comment by Tomcli** [comment]
@fenglixa we are planning to do something similar at #429. Are you planning to work on this?

**Comment by fenglixa** [comment]
Oh, I think these two are not the same task.
#429 is for the custom task support, but this one will support loop special UI displaying.
of cource, if #429 could support both of them, it will fine to me.
Thanks.

**Comment by Tomcli** [comment]
Ok, for #429 we will just have a pr for adding the new spec changes for tekton 0.19+. For the new loop status we will track with this issue.

**Comment by Tomcli** [comment]
do you want to take on this issue?

**Comment by fenglixa** [comment]
yes, sure, will take this issue.
