### ISSUE TITLE
Using kfp-tekton with Elyra results in installation failure due to conflicting dependencies

### ISSUE THREAD

**Issue by akchinSTC** [kubeflow/kfp-tekton#438]
/kind bug

**What steps did you take and what happened:**
When installing elyra with kfp-tekton as a requirement, and using the new pip package resolver, installation fails due to incompatible kfp versions, since elyra and kfp-tekton have pinned kfp to different versions, 1.1.2 vs 1.0.4 respectively. 

See: https://github.com/elyra-ai/elyra/issues/1251

Were wondering if kfp-tekton could cut a fix release with kfp requirement relaxed to >=1.0.4 ? 

**What did you expect to happen:**
Installation to complete without issue.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`): 3.7
* SDK Version: v0.5.0
* Tekton Version (use `tkn version`): na
* Kubernetes Version (use `kubectl version`): na
* OS (e.g. from `/etc/os-release`): na

**Comment by Tomcli** [comment]
We can cherry pick the 0.5.1 version to be kfp>=1.0.4

**Comment by ckadner** [comment]
@akchinSTC -- I just uploaded an unofficial `kfp-tekton` package to PyPI, version `0.5.1rc0` (https://pypi.org/project/kfp-tekton/0.5.1rc0/) which is aligned with `kfp==1.1.2`

Can you give that a try?

```shell
pip install kfp-tekton==0.5.1rc0
```

**Comment by ckadner** [comment]
@akchinSTC -- I just pushed another RC (`rc1`) to workaround a `pip` install error on mismatching version stamps `0.5.1  != 0.5.1rc0`

```shell
pip install kfp-tekton==0.5.1rc1
```

**Comment by akchinSTC** [comment]
@ckadner - so far so good! just waiting on a few other guinea pigs to test. Thanks for the quick work!!!

**Comment by ckadner** [comment]
`kfp-tekton` `v0.5.1` is available on conda-forge:

https://github.com/conda-forge/kfp-tekton-feedstock/releases/tag/v0.5.1
