### ISSUE TITLE
Refer to current Tekton sidecar output limitations somewhere in our docs

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfp-tekton#44]
https://github.com/tektoncd/pipeline/blob/master/docs/developers/README.md#handling-of-injected-sidecars

> There are known issues with the existing implementation of sidecars:
> 
> When the nop image does provide the sidecar's command, the sidecar will continue to run even after nop has been swapped into the sidecar container's image field. See the issue tracking this bug for the issue tracking this bug. Until this issue is resolved the best way to avoid it is to avoid overriding the nop image when deploying the tekton controller, or ensuring that the overridden nop image contains as few commands as possible.
> 
> kubectl get pods will show a Completed pod when a sidecar exits successfully but an Error when the sidecar exits with an error. This is only apparent when using kubectl to get the pods of a TaskRun, not when describing the Pod using kubectl describe pod ... nor when looking at the TaskRun, but can be quite confusing.

**Comment by kevinyu98** [comment]
I will look into this.
