### ISSUE TITLE
Upgrade to KFP 1.4.0

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#469]
/kind chore

**Description:**

Rebase to [KFP 1.4.0](https://github.com/kubeflow/pipelines/releases/tag/1.4.0):

- [ ] SDK (@ckadner)
- [ ] API (@Tomcli)
- [ ] UI (@drewbutlerbb4)

**Additional information:**

https://github.com/kubeflow/pipelines/releases/tag/1.4.0

**Comment by Tomcli** [comment]
@ckadner you can update the sdk to 1.4.0 since there's a sdk bug in 1.3.0 release. For API, I will wait for 1.4.0 to be official because i still see some errors in their upstream and KFP haven't announce the 1.4.0 release note yet (right now it's just a github tag).

**Comment by Tomcli** [comment]
@ckadner you can start doing the kubeflow 1.4 merge because it's official now.
