### ISSUE TITLE
Some of the samples are using argo based pipelines in samples.

### ISSUE THREAD

**Issue by ScrapCodes** [kubeflow/kfp-tekton#475]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Some of the samples are using argo based pipelines in samples.
**What did you expect to happen:**
Should be using tekton backend.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
closing this since we will stop pulling argo examples from main kfp.
