### ISSUE TITLE
Please clarify the expected behavior of dsl.Condition

### ISSUE THREAD

**Issue by chinhuang007** [kubeflow/kfp-tekton#477]
/kind question

**Question:**
According to kfp sdk doc, https://www.kubeflow.org/docs/pipelines/sdk/sdk-overview/, "dsl.Condition represents a group of ops, that will only be executed when a certain condition is met". The actual implementation seems to execute the code block under python with statement regardless the condition evaluates true or false. Is this the expected behavior?

For example, I created a simple test code.
```
import kfp
from kfp import dsl


def true_op():
    """Return string true."""
    return dsl.ContainerOp(
        name='Return true',
        image='python:alpine3.6',
        command=['sh', '-c'],
        arguments=['python -c "print(\'true\')" | tee /tmp/output'],
        file_outputs={'output': '/tmp/output'}
    )


def print_op(msg):
    """Print a message."""
    return dsl.ContainerOp(
        name='Print',
        image='alpine:3.6',
        command=['echo', msg],
    )
    

@dsl.pipeline(
    name='Conditional test pipeline',
    description='Test dsl.Condition().'
)
def cond_test_pipeline():
    get_true = true_op()
    with dsl.Condition(get_true.output == 'true'):
        print_op('This is the true branch, and condition is true')
    
    with dsl.Condition(get_true.output == 'false'):
        print_op('This is the false branch, and condition is true... should not be executed?')    


if __name__ == '__main__':
    from kfp_tekton.compiler import TektonCompiler
    TektonCompiler().compile(cond_test_pipeline, __file__.replace('.py', '.yaml'))
```

Compiled it into yaml

`apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: conditional-test-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"return-true": [{"key": "artifacts/$PIPELINERUN/return-true/output.tgz",
      "name": "return-true-output", "path": "/tmp/output"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print": [], "print-2": [], "return-true": [["output",
      "$(results.output.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Test dsl.Condition().",
      "name": "Conditional test pipeline"}'
spec:
  pipelineSpec:
    tasks:
    - name: return-true
      taskSpec:
        steps:
        - name: main
          args: [python -c "print('true')" | tee $(results.output.path)]
          command: [sh, -c]
          image: python:alpine3.6
        results:
        - {name: output, description: /tmp/output}
      timeout: 0s
    - name: print
      taskSpec:
        steps:
        - name: main
          command: [echo, 'This is the true branch, and condition is true']
          image: alpine:3.6
      when:
      - input: $(tasks.condition-1.results.status)
        operator: in
        values:
        - "true"
      timeout: 0s
    - name: print-2
      taskSpec:
        steps:
        - name: main
          command: [echo, 'This is the false branch, and condition is true... should
              not be executed?']
          image: alpine:3.6
      when:
      - input: $(tasks.condition-2.results.status)
        operator: in
        values:
        - "true"
      timeout: 0s
    - name: condition-1
      params:
      - {name: operand1, value: $(tasks.return-true.results.output)}
      - name: operand2
        value: "true"
      - {name: operator, value: ==}
      taskSpec:
        results:
        - {name: status, description: Conditional task status}
        params:
        - {name: operand1}
        - {name: operand2}
        - {name: operator}
        steps:
        - script: |-
            python -c 'import sys
            input1=str.rstrip(sys.argv[1])
            input2=str.rstrip(sys.argv[2])
            try:
              input1=int(input1)
              input2=int(input2)
            except:
              input1=str(input1)
            status="true" if (input1 $(inputs.params.operator) input2) else "false"
            f = open("/tekton/results/status", "w")
            f.write(status)
            f.close()' '$(inputs.params.operand1)' '$(inputs.params.operand2)'
          image: python:alpine3.6
    - name: condition-2
      params:
      - {name: operand1, value: $(tasks.return-true.results.output)}
      - name: operand2
        value: "false"
      - {name: operator, value: ==}
      taskSpec:
        results:
        - {name: status, description: Conditional task status}
        params:
        - {name: operand1}
        - {name: operand2}
        - {name: operator}
        steps:
        - script: |-
            python -c 'import sys
            input1=str.rstrip(sys.argv[1])
            input2=str.rstrip(sys.argv[2])
            try:
              input1=int(input1)
              input2=int(input2)
            except:
              input1=str(input1)
            status="true" if (input1 $(inputs.params.operator) input2) else "false"
            f = open("/tekton/results/status", "w")
            f.write(status)
            f.close()' '$(inputs.params.operand1)' '$(inputs.params.operand2)'
          image: python:alpine3.6
  timeout: 0s
`
Deployed to a Kubeflow cluster with kfp-tekton backend and run an experiment. Both print and print-2 are executed. Should print-2 be skipped?

**Comment by Tomcli** [comment]
@chinhuang007 not sure which version of kfp-tekton your are using. I tried your example on kfp-tekton 0.6 and 0.4, both of them skipped the print 2 task.

On kfp-tekton 0.6, you should see this to indicate print-2 task is skipped. 
<img width="466" alt="Screen Shot 2021-02-22 at 5 34 25 PM" src="https://user-images.githubusercontent.com/10889249/108791612-59c89980-7534-11eb-9fec-65a6991757c1.png">

**Comment by chinhuang007** [comment]
@Tomcli Thanks for checking!

I followed the instructions here, https://www.kubeflow.org/docs/ibm/deploy/install-kubeflow-on-iks/, to install a Kubeflow cluster using kfp-tekton. It is using https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_ibm.v1.2.0.yaml. However I don't know how to verify the kfp-tekton version in the package.

Please feel free to check my experiments in the pipelines UI, http://169.44.161.27:31380/_/pipeline/#/runs/details/d4fa675f-182a-4c9f-95ad-fb4f7b5d17d0.

![image](https://user-images.githubusercontent.com/10040293/108892909-4b768e00-75c5-11eb-86cb-fe0c454203c7.png)

**Comment by chinhuang007** [comment]
Quick follow-up... I believe kfp-tekton is 0.4.0 in the kubeflow 1.2.0 package.

**Comment by chinhuang007** [comment]
Installed kfp-tekton 0.6.0 standalone and verified the experiment result is consistent with the spec. Will close the issue now.

Just a pre-caution, the 0.4.0 packaged in the current Kubeflow 1.2.0 doesn't have proper implementation for dsl.Condition.

**Comment by Tomcli** [comment]
@chinhuang007 for kubeflow 1.2 you will need to install with `pip install kfp-tekton == 0.4.0`. kfp-tekton 0.6 changes how condition work so it may not be backward compatible.

**Comment by chinhuang007** [comment]
@Tomcli Got it. So the problem is that the yaml is created in 0.6.0 and it is not backward compatible with 0.4.0. Thanks for the clarification!
