### ISSUE TITLE
Add support for dsl.ResourceOp

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#49]
The KFP-Tekton compiler does not currently support `dsl.ResourceOp` since Tekton does not provide native support for manipulating Kubernetes resources. 

Argo provides [`ResourceTemplate`](https://github.com/argoproj/argo/blob/53a10564aebc6ee17eb8e3e121b4c36b2a334b87/pkg/apis/workflow/v1alpha1/workflow_types.go#L1395-L1417) to support "resource operations" which the Kubeflow Pipelines SDK wrapped in class [`Resource`/`ResourceOp`](https://github.com/kubeflow/pipelines/blob/1b0c91a091311abe5f43a5d3f6a90d8178516820/sdk/python/kfp/dsl/_resource_op.py#L22)

@afrittoli suggested to implement a standard (set of) Resource Tasks that could be maintained under the [`tektoncd/catalog`](https://github.com/tektoncd/catalog#tekton-catalog) project which provides a library for often reused tasks.

### Proposed implementation

In order to streamline that implementation from a compiler perspective, we could follow the precedence laid out by Argo's `ResourceTemplate`, and create a Tekton Task with the following parameters:

- `action`: `['get', 'create', 'apply', 'delete', 'replace', 'patch']` -- the action to perform to the resource
- `merge_strategy`: `['strategic', 'merge', 'json']` -- the strategy used to merge a patch, defaults to "strategic"
- `success_condition`: a label selector expression which describes the `success` condition
- `failure_condition`: a label selector expression which describes the `failure` condition
- `manifest`: the kubernetes manifest

### Link to issue in `tektoncd/catalog`

[Task(s) to manage kubernetes resources in a cluster #233](https://github.com/tektoncd/catalog/issues/233)

### Additional information

Excerpt from [KFP/Argo-vs-Tekton capabilities spreadsheet](https://docs.google.com/spreadsheets/d/1LFUy86MhVrU2cRhXNsDU-OBzB4BlkT9C0ASD3hoXqpo/edit#gid=979402121&range=22:22)

KFP DSL (kfp.dsl) | Argo Workflow (Current Implementation) | Tekton v0.10.0 (Potential implementation) | Notes | Tekton Backend
-- | -- | -- | -- | --
ResourceOp | ResourceTemplate | Tasks to create, patch, delete, etc. resourcesThe tasks have to be defined, and they could live in the catalog. This is not natively supported by Tekton. | Tekton could define a `ResourceTask`, similar to what Argo does with `ResourceTemplate`, but it is not required to implement ResourceOp. | Workaround

**Comment by ckadner** [comment]
@fenglixa see issue in `tektoncd/catalog`:

[Task(s) to manage kubernetes resources in a cluster #233](https://github.com/tektoncd/catalog/issues/233)

**Comment by Tomcli** [comment]
This is an example attribute output/results when using resourceOps on Argo.
https://github.com/kubeflow/pipelines/blob/master/sdk/python/tests/compiler/testdata/resourceop_basic.py#L41
https://github.com/kubeflow/pipelines/blob/master/sdk/python/tests/compiler/testdata/resourceop_basic.yaml#L44-L46

The Argo go implementation is under https://github.com/argoproj/argo/blob/master/workflow/executor/resource.go#L22-L76

**Comment by Tomcli** [comment]
For the first phrase we can work with just `get, create, apply` actions and the return defined outputs from the resource status yaml.

**Comment by vincent-pli** [comment]
Do we need `success_condition` and `failure_condition`, that's little complex to implement.
and output is a expression, right? 
so we need define parameters in tekton task, please correct me:
- action
- merge-strategy
- manifest
- output
- success_condition
- failure_condition

**Comment by fenglixa** [comment]
Get resourceOp example fails as secrets creation is forbidden error, KFP already update the resourceOps example to jobs, see [issue](https://github.com/kubeflow/pipelines/issues/2623) and [PRs](https://github.com/kubeflow/pipelines/pull/2274) for details. I will change to use updated example as well.

**Comment by fenglixa** [comment]
> so we need define parameters in tekton task, please correct me.

@vincent-pli , I think you are correct. @ckadner @Tomcli, please comments. Thanks.

**Comment by vincent-pli** [comment]
And `argo` attach `output` as annotation to `pod` (workflow generated?), what's he behavior in kfp?

**Comment by Tomcli** [comment]
> Get resourceOp example fails as secrets creation is forbidden error, KFP already updated the resourceOps example to jobs, see [issue](https://github.com/kubeflow/pipelines/issues/2623) and [PRs](https://github.com/kubeflow/pipelines/pull/2274) for details. I will change to use updated example as well.

By default KFP doesn't have permission to create most of the Kubernetes resource such as secret and configmap. The assumption is the admin should update the pipeline-runner with the necessary rbac permission for creating secret/configmap, pvc, and crd such as tfjob.

**Comment by Tomcli** [comment]
> Do we need `success_condition` and `failure_condition`, that's little complex to implement.
> and output is a expression, right?
> so we need define parameters in tekton task, please correct me:
> 
> * action
> * merge-strategy
> * manifest
> * output
> * success_condition
> * failure_condition

Here is the implementation for resourceOps https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/dsl/_resource_op.py#L69-L74

We are expecting 5 input parameters `action, merge-strategy, manifest, success_condition, failure_condition` and a list of results define as the outputs. The result syntax should support getting certain field from the deployed manifest such as `{.metadata.name}`.

For the first version of resourceOp, we are hoping that it support actions `get, create, apply`, taking `manifest`, and create a list of `Tekton results` for attribute_outputs. This should be enough for me to work on VolumeOp. Delete action is also important but it's not a blocker for the VolumeOp.

`merge-strategy, success_condition, failure_condition` and other actions might be complicated, so we can implement them later in some followup PRs.

**Comment by vincent-pli** [comment]
@Tomcli thanks.
I will write `output` to `tekton/result/output`, is that satisfy you?

**Comment by Tomcli** [comment]
yes, that should work for me.

**Comment by vincent-pli** [comment]
@Tomcli Do we expect set `owner reference` to the resource created?

**Comment by Tomcli** [comment]
For now, we don't have to set `ownerReference` for the users since it's also not part of the Argo feature.
