### ISSUE TITLE
automate labels and annotations for pipeline cache

### ISSUE THREAD

**Issue by vincent-pli** [kubeflow/kfp-tekton#497]
/kind feature

**Description:**
We has done the implements for `cache server` to meet the `tekton` for backend. and try to enable the function in `DSL` side.

Basically, to enable the `cache` feature just need add several specific `label`s to the sub task.
By review the original implements(Argo), it add the label in the api level(a global setting), it's not work in `tekton`, in `tekton` scenario, we expect enable `cache` in sub tasks, since the `output cache` is based on `Result`, not every task has result.

For now, we just let user add the label manually in DSL code, like this:
```
    task1.add_pod_label('pipelines.kubeflow.org/cache_enabled', "true")
    task1.add_pod_annotation('tekton.dev/template', "")
```

But I think we can make it more grace to wrapper/abstract it, maybe a parameter: `enalbe-cache` and compiler will add these `label`s automatically。

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by drewbutlerbb4** [comment]
@vincent-pli 
I have an initial PR #507 which adds the labels so that caching is enabled for every task. As you noted this allows any task with `Results` to be cached. Is the ask here to also enable caching for tasks without `Results` or does this PR fulfill the request?

**Comment by vincent-pli** [comment]
@drewbutlerbb4 
I append my comments in the pr, p please take a look, thanks
