### ISSUE TITLE
Allow reviewers to apply and remove issue labels

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#53]
@animeshsingh -- we have a few un- and/or mislabeled issues. The current project permissions do not allow reviewers to add/change/remove labels. It does not appear that the commands outline in the [`k8s-ci-robot` command help](https://prow.k8s.io/command-help?repo=kubeflow%2Fkfp-tekton) work.

**Comment by animeshsingh** [comment]
@jlewi how can we get this addressed?

**Comment by ckadner** [comment]
@jlewi could you help us to get project reviewers permission to add and remove issue labels for the `kfp-tekton` project?

**Comment by jlewi** [comment]
The bot command should work.
Example 

/kind question
/area engprod

**Comment by jlewi** [comment]
For the bot commands to work you need to be a member of the GitHub org.
GitHub now has the IssueTriage role which might be fine grained enough give people more access on that role.

That said we want all GitHub permissions to be administered declaratively using GitOps using periobolos.
https://github.com/kubernetes/test-infra/blob/eb64dfdaf1fb86024ad153b6e4caef7135cd3fdf/prow/cmd/peribolos/README.md

So if you need more permissions please investigate whether this would be supported today with our existing setup.
https://github.com/kubeflow/internal-acls/blob/master/github-orgs/kubeflow/org.yaml

And if not maybe suggest what changes are need to support it.

**Comment by ckadner** [comment]
@jlewi -- Thanks, it works now (mostly). There seemed to have been a delay in the bot when I first noticed issues and then I tripped up over `/kind documentation` not working

**Comment by ckadner** [comment]
> label `documentation` not working

Seems like the `k8s-ci-robot` cannot apply the label `/documentation` via issue comments, but comment `/area docs` will add the label `area/docs`

I just noticed I can click on the `LABEL` link in the Kubernetes Prow Robot [command help] (https://prow.k8s.io/command-help):
> **_label_**
> **Description**
> 
> The label plugin provides commands that add or remove certain types of labels. Labels of the following types can be manipulated: 'area/*', 'committee/*', 'kind/*', 'language/*', 'priority/*', 'sig/*', 'triage/*', and 'wg/*'. More labels can be configured to be used via the /label command.

**Comment by ckadner** [comment]
Thanks @jlewi 

/close
