### ISSUE TITLE
Update UI to render user defined Tekton custom task

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#535]
/kind feature

**Description:**
We introduced new features that allow users to define Tekton custom task in KFP. However, the UI needs to be updated in order to render any user defined custom task.
e.g. we need the UI to render this condition example
https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/condition_custom_task.yaml

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by pugangxa** [comment]
So do we plan to have UI for custom task or even for the content of the custom task? Take loop for example, do we just show the loop as a whole custom task or user can click it to deep into the pipelines created for the loop? 
Considering the diversity of custom task I think we cannot support this granularity for all of the custom tasks but for some typical ones right?
