### ISSUE TITLE
Add support for set_image_pull_secrets

### ISSUE THREAD

**Issue by kevinyu98** [kubeflow/kfp-tekton#54]
Check whether I can use this as an example:
[set_image_pull_secrets](https://github.com/kubeflow/pipelines/blob/264ff37c1e21b413ec1ccc5049541429dc2d9fd5/sdk/python/kfp/dsl/_pipeline.py#L66)

**Comment by ckadner** [comment]
> Check whether I can use this as an example:
set_image_pull_secrets

No, we are not changing the implementation of DSL in KFP ~[kubeflow/pipelines/sdk/python/kfp/dsl/_pipeline.py](https://github.com/kubeflow/pipelines/blob/264ff37c1e21b413ec1ccc5049541429dc2d9fd5/sdk/python/kfp/dsl/_pipeline.py#L66)~

The code to be added/modified should be in [sdk/python/kfp_tekton/compiler/compiler.py#_create_pipeline_workflow](https://github.com/kubeflow/kfp-tekton/blob/ed3afe051ac293ad8a2c53a6c907b346fda36603/sdk/python/kfp_tekton/compiler/compiler.py#L72-L141) 
... following how it's done in the KFP SDK here:
https://github.com/kubeflow/pipelines/blob/1b0c91a091311abe5f43a5d3f6a90d8178516820/sdk/python/kfp/compiler/compiler.py#L678-L682
```Python
    if len(pipeline_conf.image_pull_secrets) > 0:
      image_pull_secrets = []
      for image_pull_secret in pipeline_conf.image_pull_secrets:
        image_pull_secrets.append(convert_k8s_obj_to_json(image_pull_secret))
      workflow['spec']['imagePullSecrets'] = image_pull_secrets
```

**Comment by kevinyu98** [comment]
Tried to create service account and which can pull the image secret, but Tommy is worried that the we may not have permission to clean up the service account. Have issue to pull the image from podtemplate approach. I have opened an issue on tekton.
[2339](https://github.com/tektoncd/pipeline/issues/2339)

**Comment by NikeNano** [comment]
This pr: https://github.com/tektoncd/pipeline/pull/2547 in Tekton/pipelines should be able to help solve this problem. I can work on it together with @JohanWork when/if the PR is merged.

**Comment by NikeNano** [comment]
This is now merged on the [tekton side](https://github.com/tektoncd/pipeline/pull/2547/files ) @johanWork
