### ISSUE TITLE
[Any-Sequencer][Condition]Enhance the output messages.

### ISSUE THREAD

**Issue by huixa** [kubeflow/kfp-tekton#551]
**Test the any-sequencer condition #539 , some output messages which it's better to enhance:**

**Env:**
build the env for any-sequencer from kfp-tekton/tekton-catalog/any-sequencer

===================
**Update 1:**
**When trigger the any by one condition, the output message as below:**
_[root@symtest21 test]# kubectl -n kubeflow logs any-sequencer-any-test-lnbrq-pod-w4698
time="2021-04-20T05:40:28Z" level=info msg="Starting to watch taskrun for 'task1,task3' and condition in kubeflow/any-sequencer."
time="2021-04-20T05:40:47Z" level=info msg="The TaskRun of flipcoin succeeded."
[root@symtest21 test]#_

**Suggestion:**
1)Whether could add the condition information in the first line's log:
"Starting to watch taskrun for 'task1,task3' and condition in kubeflow/any-sequencer."

2)Whether could add the related messages when the meet the condition.

**Comment by huixa** [comment]
@pugangxa , please help handle this one. Thanks.

**Comment by pugangxa** [comment]
/assign 
Agree we can add detailed message.

**Comment by huixa** [comment]
use the new code to test it, it's ok.
