### ISSUE TITLE
[Any-Sequencer][Condition]any-test cannot exit when the condition does not meet.

### ISSUE THREAD

**Issue by huixa** [kubeflow/kfp-tekton#552]
**Test the any-sequencer condition #539 , some output messages which it's better to enhance:**

**Env:**
build the env for any-sequencer from kfp-tekton/tekton-catalog/any-sequencer

**Issue:**
When the condition does not meet, the any-test will watch forever, don't exit.

**Configure:**
    - name: any-test
      taskSpec:
        steps:
        - name: main
          args:
          - --namespace
          - $(params.pipelineRun-namespace)
          - --prName
          - $(params.pipelineRun-name)
          - --taskList
          - 
          - -c
          - results_flipcoin_output1 == 'heads'
          
**Result:**
[root@symtest21 test]# kubectl -n kubeflow logs any-sequencer-any-test-wh6ds-pod-6s4hx
time="2021-04-20T06:03:13Z" level=info msg="Starting to watch taskrun for '' and condition in kubeflow/any-sequencer."
time="2021-04-20T06:03:30Z" level=info msg="The TaskRun of flipcoin succeeded."
time="2021-04-20T06:03:30Z" level=info msg="The result output1 does not exist in taskrun flipcoin."
time="2021-04-20T06:03:30Z" level=info msg="The condition results_flipcoin_output1 == 'heads' for the task flipcoin does not meet."
[root@symtest21 test]# 

[root@symtest21 test]# kubectl -n kubeflow get po
NAME                                               READY   STATUS      RESTARTS   AGE
any-sequencer-any-test-wh6ds-pod-6s4hx             1/1     Running     0          8m6s
any-sequencer-flipcoin-9699p-pod-g29r4             0/1     Completed   0          7m48s
any-sequencer-task1-srsv6-pod-f5842                0/1     Completed   0          8m6s
any-sequencer-task2-x24s5-pod-m44zt                0/1     Completed   0          8m6s
any-sequencer-task3-fgsf7-pod-lb9jb                0/1     Completed   0          8m6s

**Expect Result:**
When does not meet the condition or does not find the condition in taskrun, should exit the any-test.

**Comment by huixa** [comment]
@pugangxa , please help handle this one. Thanks.

**Comment by pugangxa** [comment]
/assign
OK will take a look, thanks!

**Comment by Udiknedormin** [comment]
@huixa @pugangxa It seems to me it should put the AnySequencer into "skipped" tasks in such a case, so that tasks that have a dependency on it would not run as if it exited successfully.

**Comment by pugangxa** [comment]
In fact I already do it this way to append to failed task when condition not meet. I found it's because in yaml if taskList is empty or "" it will still be accepted in go. 
I already come up with a fix for these issues and will PR tomorrow after full testing.

**Comment by Tomcli** [comment]
/close
by #557

**Comment by huixa** [comment]
**use the new code to test it, it's ok.**

**case 1: when no the condition and task list:**
_[root@symtest21 kfp-tekton]# 
time="2021-04-23T03:07:20Z" level=info msg="Should provide either taskList or conditions to watch."
[root@symtest21 kfp-tekton]#_ 

**case 2: when all the conditions failed:**
_[root@symtest21 kfp-tekton]# kubectl -n kubeflow logs any-sequencer-any-test-qxq7p-pod-bgf7t
time="2021-04-23T03:27:21Z" level=info msg="Starting to watch taskrun for '' and condition in kubeflow/any-sequencer."
time="2021-04-23T03:27:24Z" level=info msg="The TaskRun of flipcoin1 succeeded."
time="2021-04-23T03:27:24Z" level=info msg="The condition results_flipcoin1_output1 == 'heads3' for the task flipcoin1 does not meet."
time="2021-04-23T03:27:40Z" level=info msg="The TaskRun of flipcoin succeeded."
time="2021-04-23T03:27:40Z" level=info msg="The condition results_flipcoin_output1 == 'heads3' for the task flipcoin does not meet."
time="2021-04-23T03:27:40Z" level=info msg="All specified TaskRun(s) failed."
[root@symtest21 kfp-tekton]#_
