### ISSUE TITLE
Pipeline level timeout

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfp-tekton#56]
timeout for whole pipeline: run tkn p start pipeline-includes-two-steps-which-fail-randomly --showlog --timeout 180s

Tekton takes it at runtime, so we need to figure out transferring from DSL to runtime execution as part of the API/backend work

**Comment by ckadner** [comment]
can we leave it up to the user who runs the pipeline to specify a timeout at the pipeline level?

**Comment by fenglixa** [comment]
Generate pipelinerun.yaml could address this issue.

**Comment by fenglixa** [comment]
fixed by #68 
/close
