### ISSUE TITLE
verify upcoming Tekton 0.24 on kfp-tekton

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#570]
/kind feature

**Description:**
Upcoming Tekton 0.24 release could have critical change to the Tekton home directory behavior. Our internal team will be moving to it soon, so we need to verify it before it breaks our code.

This will go in our 0.9.0 release since Tekton 0.24 is not out yet.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
master branch doesn't have issue for the path sensitive examples. The home directory behavior in Tekton 0.24 are not in master branch yet. Will verify again when Tekton 0.24 is officially released.

**Comment by Udiknedormin** [comment]
@Tomcli It looks like 0.24 is [officially released](https://github.com/tektoncd/pipeline/releases/tag/v0.24.0) now.

**Comment by Tomcli** [comment]
@Udiknedormin I tested with new Tekton 0.24 and don't see any problem with it. We already disabled the home and work directory overwrite when we deploy Tekton as part of Kubeflow since the early 2020. The only way this can cause problem is from the user container. Let us know if you see any issue on Tekton 0.24 release and we can fix it accordingly.

**Comment by Udiknedormin** [comment]
@Tomcli We disabled it on our side too and saw no problems. We haven't tested any other stuff from 0.24 yet though.

**Comment by Tomcli** [comment]
/close
we don't see any issue for tekton 0.24
