### ISSUE TITLE
Cache server only effect in certain namespace for now, should has ability to watch all namespaces

### ISSUE THREAD

**Issue by vincent-pli** [kubeflow/kfp-tekton#580]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]
For now, `cache server` will only effect on one certain `namespace`(namespace: kubeflow), it should has ability to watch all namespaces.

To enable such ability, there are two steps required:

1. `cache server` has variables `namespace_to_watch` to define the `namespace` it effected: https://github.com/kubeflow/kfp-tekton/blob/de00ccadef3214e85c252a75906455d4fe3ee94e/manifests/kustomize/base/cache/cache-deployment.yaml#L63
set `--namespace_to_watch=`

2. Change https://github.com/kubeflow/kfp-tekton/blob/master/manifests/kustomize/base/cache/cache-role.yaml to `clusterrole` and change https://github.com/kubeflow/kfp-tekton/blob/master/manifests/kustomize/base/cache/cache-rolebinding.yaml to `clusterrolebinding`

So we need either add these step to https://github.com/kubeflow/kfp-tekton/tree/master/backend/src/cache or enable option in `kustomize`

@Tomcli what do you think?

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
@vincent-pli for multi-users mode, we will patch these manifests to the cache server
https://github.com/kubeflow/kfp-tekton/tree/master/manifests/kustomize/base/installs/multi-user/cache

I found that the cache permission didn't get enough permission to watch taskruns for all namespace, so I PRed #581 to fix this issue.

**Comment by Tomcli** [comment]
In short, the multi-users manifests will patch the `NAMESPACE_TO_WATCH` env to `''` to let the cache server watch all namespace. Then it also patch the necessary clusterrole and clusterrolebinding permission as well.
