### ISSUE TITLE
User-defined resource-based custom tasks

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#590]
/kind feature

**Description:**
It's currently possible to define a new custom task in the user land. However, it's not possible to generate neither `taskSpec` nor a new resource for that component, like the `TektonCompiler` itself does for `dsl.ParallelFor`. Due to that, what is possible to achieve with custom task is limited.

Without adding support for either `taskSpec` (when it's merged into Tekton repo) or new resource generation, user-defined custom tasks are limited to tasks which do not require any configuration aside from parameters to be passed to them.

One particularly interesting use-case for that kind of custom-tasks is [pipelines-in-pipelines](https://github.com/tektoncd/experimental/tree/main/pipelines-in-pipelines). Those could come handy in `finally` section too, considering how it essentially lacks `runAfter`.

**How to do it?**
Because custom resources may contain arbitrary data, I think it's ok if the user would have to specify the yaml manually or quasi-manually (e.g. allowing string interpolation of `PipelineParam`). In case of pipelines-in-pipelines, the user could create a pipeline, representing the resource, generate yaml for it, and then pass that yaml to the resource-based custom task in another pipeline.

**Comment by Tomcli** [comment]
I can add some new fields to the containerop to take raw yaml as custom task spec. As for custom task that needs specialized processing such as pipelines-in-pipelines, we will need to ask users to implement an inheritance class that has similar functions as how we generate pipelineloop CR.

**Comment by Udiknedormin** [comment]
@Tomcli The extra-fields and custom resource generation / custom task spec is much more important. As I said, the pipelines-in-pipelines can be handled if it's implemented (not an elegant solution but it works).

**Comment by Tomcli** [comment]
#593 able to accept the custom task spec as it and generate a new yaml for it. If there are a list of custom tasks you want to have more specific DSL integration, let us know and we will evaluate them.

As for pipelines-in-pipelines, personally I would recommend to see can we work around with pipeline loop. As far as I know, pipelines-in-pipelines only has 2-3 active reviewers and we need at least 2 approvers in order to add new features or fix any bug on pipelines-in-pipelines.
