### ISSUE TITLE
Make SDK compile nested recursion with conditions in Tekton

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#599]
/kind feature

**Description:**
Currently when compiling any nested recursion pipeline to Tekton, the compiler doesn't place the nested loop reference correct. Using the below example,
```python
from kfp import dsl


def flip_coin_op():
    """Flip a coin and output heads or tails randomly."""
    return dsl.ContainerOp(
        name='Flip coin',
        image='python:alpine3.6',
        command=['sh', '-c'],
        arguments=['python -c "import random; result = \'heads\' if random.randint(0,1) == 0 '
                  'else \'tails\'; print(result)" | tee /tmp/output'],
        file_outputs={'output': '/tmp/output'}
    )


def print_op(msg):
    """Print a message."""
    return dsl.ContainerOp(
        name='Print',
        image='alpine:3.6',
        command=['echo', msg],
    )


@dsl.pipeline(
    name='nested recursion pipeline',
    description='shows how to use graph_component and nested recursion.'
)
def flipcoin(maxVal=12):
  @dsl._component.graph_component
  def flip_component(flip_result, maxVal):
    @dsl._component.graph_component
    def flip_component_b(flip_result_b, maxVal_b):
      with dsl.Condition(flip_result_b == 'heads'):
        print_flip_b = print_op(flip_result_b)
        flipB = flip_coin_op().after(print_flip_b)
        flip_component_b(flipB.output, maxVal_b)
    with dsl.Condition(flip_result == 'heads'):
      flip_component_b(flip_result, maxVal)
    with dsl.Condition(flip_result == 'heads'):
      print_flip = print_op(flip_result)
      flipA = flip_coin_op().after(print_flip)
      flip_component(flipA.output, maxVal)

  flip_out = flip_coin_op()
  flip_loop = flip_component(flip_out.output, maxVal)
  print_op('cool, it is over. %s' % flip_out.output).after(flip_loop)


if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  # For Argo, uncomment the line below
  # from kfp.compiler import Compiler
  Compiler().compile(flipcoin, __file__.replace('.py', '.yaml'))
```

When compiled to Argo, it will look like this
![argo](https://user-images.githubusercontent.com/10889249/119419952-27a01280-bcb0-11eb-8445-6e1b17133ac6.png)

However, when compiled to Tekton, the loop reference is generated in the wrong pipeline
![tekton-error](https://user-images.githubusercontent.com/10889249/119419989-3e466980-bcb0-11eb-9052-6a9ec4454582.png)

We need to fix the nested recursion reference like below
![tekton-correct](https://user-images.githubusercontent.com/10889249/119420012-4d2d1c00-bcb0-11eb-8c59-d02df2200b46.png)

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
#591 has another example for when using custom task

**Comment by Tomcli** [comment]
@pugangxa are you able to take on this issue? I'm not sure which part of the code handles the loop references for recursion.

**Comment by pugangxa** [comment]
> @pugangxa are you able to take on this issue? I'm not sure which part of the code handles the loop references for recursion.

Sure, I will take a look.

**Comment by pugangxa** [comment]
Seems it works for me. Using the example above, after fixed a key error, seems the nested recursion taskref is generated. @Tomcli

**Comment by Udiknedormin** [comment]
@pugangxa @Tomcli What's the status of this issue?

**Comment by pugangxa** [comment]
Just wait for review and approve. @Tomcli
