### ISSUE TITLE
AnySequencer: for success, the status is "Succeeded" but should be "Completed"

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#603]
/kind bug

As described in title: when an AnySequencer finishes execution successfully, its `status` is "Succeeded" instead of "Completed".

**Comment by Tomcli** [comment]
we probably need to change this line? https://github.com/kubeflow/kfp-tekton/blob/master/tekton-catalog/any-sequencer/cmd/root.go#L51

/cc @pugangxa 
is this what your team want to change?

**Comment by pugangxa** [comment]
@Udiknedormin In my opinion, when an AnySequencer finishes execution it's completed so failed or skipped is also completed right? So now there's status `Succeeded`, `Failed` and `Skipped`, I think if it's not completed `Failed` and `Skipped` why can not it be `Succeeded`?

BTW, I saw other discussion in your repo, if there's more enhancements needed, please summarize and I can do it all at one time, thanks.

**Comment by Udiknedormin** [comment]
@pugangxa I'm not aware of any more issues with AnySequencer. Other than that value of status, it seems to be working fine to me.

**Comment by pugangxa** [comment]
> @pugangxa I'm not aware of any more issues with AnySequencer. Other than that value of status, it seems to be working fine to me.

OK, then I will fix this now.
