### ISSUE TITLE
Create a validation CLI for commonly used Tekton custom task CRDs

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#611]
/kind feature

**Description:**
The Tekton CLI only can verify official Tekton CRDs but not custom task CRDs. Therefore we often time can see things are compiled and able to run without complain even though the custom task CRD syntax is completely wrong. Thus, we need to create some CLI to verify the common Tekton custom task CRDs that we use such as pipeline loop.

Goal: Create a CLI/script to run the below validation locally
https://github.com/kubeflow/kfp-tekton/blob/master/tekton-catalog/pipeline-loops/pkg/apis/pipelineloop/v1alpha1/pipelineloop_validation.go#L30

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ScrapCodes** [comment]
One of the challenges I am facing in implementing this is, validations are not same for embedded spec and normal spec. For example, it is ok for an embedded spec to not have field `metadata.name` and not for normal spec or PipelineLoop.

**Comment by fenglixa** [comment]
Thanks @ScrapCodes , I think it's OK to only validate the madatory filed, and it will be better if we can ensure the format of the custom task definition is correct.
I am glad to review any PRs for this issue. : )

**Comment by ScrapCodes** [comment]
@fenglixa Thank you ! 

I have opened my WIP PR #614 , you can take a look.
