### ISSUE TITLE
Update SDK to support embedded spec for custom task

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#627]
/kind feature

**Description:**
This issue needs to build on top of #626 

Update SDK to support embedded spec for custom task instead of using taskRef.

Requirements:
1. Have a flag (python variable) to switch back to the old taskRef behavior for backward compatibility.
2. Make parallel pipeline loops and user custom task to use taskSpec (recursive loop will keep using taskRef because it needs  self reference)

High level TODOs:
1. Update this section to embed the pipeline loop crd as taskSpec instead of an extra file. This way help us to keep both compatibility. Please be aware that we only want to embed spec from parallel for loop. https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/compiler.py#L1310-L1315
2. Update the user defined custom task to use taskSpec similar to the above situation.  https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/compiler.py#L1319-L1321
     In case some custom task doesn't support taskSpec, we need to update the user defined custom task logic to support the old taskRef as well. https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/compiler/compiler.py#L733-L777
     KFP Tekton Custom task documentation: https://github.com/kubeflow/kfp-tekton/blob/master/guides/advanced_user_guide.md#using-tekton-custom-task-on-kfp-tekton

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
cc @ScrapCodes 

We can split this issue into two part in case we need to split the work. Can you work on the first TODO in this issue?

**Comment by ScrapCodes** [comment]
Thanks @Tomcli, on it.
