### ISSUE TITLE
Single character parameters need to have double quote to avoid yaml keyword conflicts

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#664]
I think this is a bug, we should have double quote on single character parameter for n and y to avoid this issue. For now I will lgtm and open another issue for it

_Originally posted by @Tomcli in https://github.com/kubeflow/kfp-tekton/pull/660#discussion_r666403707_

**Comment by Tomcli** [comment]
to reproduce this issue, use either `n` or `y` as the parameter name or key and the issue will be reproduced. We need to put double quotes on them to avoid these conflicts

**Comment by pugangxa** [comment]
/assign
Strange it works for me with double quotes on. Anyway I will make it clear.

**Comment by pugangxa** [comment]
I found when I run the file conditions_and_loops.py(change n1 back to n) directly then the yaml would be fine. But in test with GENERATE_GOLDEN_YAML being true then it would be error. 
Seems it's due to yaml dump/load, see https://github.com/yaml/pyyaml/issues/247
