### ISSUE TITLE
Migrate components away from containerOp

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#670]
/kind feature

**Description:**
We need to update all our helper functions and examples to use component.yaml instead of containerOp because containerOp is going to be removed in the v2 release.

- [ ] [Hyperparameter tuning using Katib](/samples/katib)
- [ ] [Training and Serving Models with Watson Machine Learning](/samples/watson-train-serve#training-and-serving-models-with-watson-machine-learning)
- [x] [Lightweight python components example](/samples/lightweight-component)
- [x] [Pipeline with Nested loops](/samples/nested-loops)
- [x] [Using Tekton Custom Task on KFP](/samples/tekton-custom-task)
- [x] [The flip-coin pipeline using custom task](/samples/flip-coin-custom-task)

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
@yhwang can you take care of 
- [ ] https://github.com/kubeflow/kfp-tekton/tree/master/samples/nested-pipeline
- [ ] https://github.com/kubeflow/kfp-tekton/tree/master/samples/flip-coin
- [ ] https://github.com/kubeflow/kfp-tekton/tree/master/samples/trusted-ai

some of them should be partially using component.yaml already

**Comment by yhwang** [comment]
try to note down the issues while updating testcases and samples:
- not sure how to use component.yaml with `dsl.InputArgumentPath`
  - sdk/python/tests/compiler/testdata/input_artifact_raw_value.py
- NotImplementedError: dsl.graph_component is not yet supported in KFP v2 compiler
   - sdk/python/tests/compiler/testdata/long_recursive_group_name.py
   - sdk/python/tests/compiler/testdata/loop_in_recursion.py
   - sdk/python/tests/compiler/testdata/nested_recur_custom_task.py
   - sdk/python/tests/compiler/testdata/nested_recur_runafter.py

**Comment by Udiknedormin** [comment]
@Tomcli @yhwang 
What's the status of this issue?

**Comment by Tomcli** [comment]
@Udiknedormin 
All the current examples in KFP-Tekton are migrated to component.yaml. The two examples that didn't check are the also in component.yaml but their service API was broken when we were testing it. Although containerOp is deprecated, it will continue to work in V1 KFP and KFP-Tekton.
