### ISSUE TITLE
Question: support ParallelFor params which was defined in input/out

### ISSUE THREAD

**Issue by fenglixa** [kubeflow/kfp-tekton#70]
If loop parameters are static, then we can parallel instance several taskrun with different parameter to workaround it.
But if the loop parameters are from the input/output parameter of pipeline/tasks, how it works for tekton pipeline?
e.g: https://github.com/kubeflow/pipelines/blob/master/samples/core/loop_parameter/loop_parameter.py

**Comment by fenglixa** [comment]
kind/question

**Comment by fenglixa** [comment]
@afrittoli @animeshsingh @vincent-pli @ckadner @Tomcli  could you help?

**Comment by fenglixa** [comment]
Since Tekton doesn't have loop/recursion support, PR #67 will workaround the static parameters by flatten the loop as taks list.
But if it's  dynamic params (e.g: input/output), seems we still need Tekton have this feature to address it.

**Comment by animeshsingh** [comment]
I belive we need inputs from @afrittoli @vincent-pli for this. Is there a view of how any pipelines currently are using dynamic links?

**Comment by afrittoli** [comment]
We started looking at this kind of feature on Tekton side. Until we implement it I don't think there's a way to support the dynamic case.
We could perhaps have a single running over the params in a loop. It would not be parallel but it might work.
