### ISSUE TITLE
Develop (not copy) E2E example(s)

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#71]
We need to develop a few succinct examples, which demonstrate some of the benefits of generating Tekton over Argo. We could start by picking one or two example from Kubeflow Pipelines [core samples](https://github.com/kubeflow/pipelines/tree/master/samples/core) but we should not simply duplicate files in this repo.

One of those examples should serve as the main reference in our README and future docs and our end-to-end testing.

_Originally posted in https://github.com/kubeflow/kfp-tekton/pull/69#issuecomment-605291518_

**Comment by ckadner** [comment]
@Tomcli @fenglixa

**Comment by fenglixa** [comment]
I tried to add mnist example but blocked by resourceOps,  will add it later after resourceOps impletmented.

**Comment by fenglixa** [comment]
@ckadner do you know who is working on resourceOps recently, if not, I can have a try.
