### ISSUE TITLE
kfp dependency pin in 1.0.0 breaks pipeline version upload API calls

### ISSUE THREAD

**Issue by ptitzler** [kubeflow/kfp-tekton#745]
/kind bug

**What steps did you take and what happened:**
`kfp-tekton 1.0` sdk is pinned to [`kfp==1.7.2`](https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/setup.py#L57), which causes https://github.com/elyra-ai/elyra/issues/2085 (generally speaking upload of pipeline _versions_ will always fail). Would a pin to a later version be possible so Elyra can start using kfp-tekton > 0.8.x?

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
@ptitzler which kfp version elyra is using right now? We can have a 1.0.1 release on the new kfp version because that bug was fixed after we published our initial.

**Comment by Tomcli** [comment]
@ptitzler new release is over here https://pypi.org/project/kfp-tekton/1.0.1/
you should able to put both kfp==1.7.1 and kfp-tekton==1.0.1 in the same requirements.txt
