### ISSUE TITLE
Map Argo variables to Tekton varaibles.

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#78]
KFP uses [Argo variables](https://github.com/argoproj/argo/blob/master/docs/variables.md) to refer artifact locations and exit ops status. Therefore, we want to map as much variables in Argo as possible since issues https://github.com/kubeflow/kfp-tekton/issues/64 and other pipelines assume those variable can be interpreted during execution. 

As of today, Tekton variables $() only has inputs and outputs params on the task level. For other variables, we will try to map them with env variables using Kubernetes FieldRef Parameter. 

However, many Argo variables are still not possible with Tekton variables and pure Kubernetes FieldRef Parameter. Thus, we will raise a warning for users to avoid using them in a pipeline.

**Comment by Tomcli** [comment]
Currently this is the equivalent variable matching i found.
argo -> tekton
`{{inputs.parameters.%s}}` -> `$(inputs.params.%s)`
`{{outputs.parameters.%s}}` -> `$(results.%s.path)`

Since we don't have other equivalent matching for the rest of the [argo variables](https://github.com/argoproj/argo/blob/master/docs/variables.md), we will prompt a warning when those argo variables are used. Since KFP also don't recommend to use Argo variables because it requires specific knowledge on Argo pipeline. 

The other places argo variables are used is during artifact output path. We can workaround with this by creating our own s3/gcs tasks to parse artifact output path using environment variables. This way we don't have to rely on Tekton to replace those workflow variables during execution. However, this means we need to maintain our own s3/gcs task for artifact storing.

**Comment by ckadner** [comment]
Is this what you meant with ...
>  Handler for checking Argo specific params, find equivalent for Tekton

in https://github.com/kubeflow/kfp-tekton/issues/18#issuecomment-600734388 ?

**Comment by Tomcli** [comment]
yes
