### ISSUE TITLE
Pipelineloop should support to iterate with an string with separator char

### ISSUE THREAD

**Issue by wzhanw** [kubeflow/kfp-tekton#788]
/kind feature

**Description:**
Current pipeline loop only supports to iterate from `iterateParam` with string value like:
```
value: '["I am the first one", "I am the second one", "I am the third one"]'
```

I would like to introduce a new field `iterateParamSeparator` to allow user to pass the separator char and allow us to split the iterateParam as a string array for the loop.

This field is optional, it only works with string type param.

eg: 
```
iterateParam= "aaa|bbb|ccc|ddd"
iterateParamSeparator="|"
```

**Comment by wzhanw** [comment]
@pugangxa @Tomcli  if you agree this this enhancement, I'm going to create the PR Thanks.

**Comment by Tomcli** [comment]
@wzhanw is the `'["I am the first one", "I am the second one", "I am the third one"]'` format still supported? We want to ensure it won't break any backward compatibility.

**Comment by Tomcli** [comment]
I'm okay with the new proposed iterateParam. FYI @Udiknedormin are you aware of this change?

**Comment by pugangxa** [comment]
@wzhanw As discussed, there's multiple format for loop parameters, like `from/to`, list and string with separators. It's OK to have this feature for the format of `string with separators`, thanks.

**Comment by wzhanw** [comment]
> @wzhanw is the `'["I am the first one", "I am the second one", "I am the third one"]'` format still supported? We want to ensure it won't break any backward compatibility.

sure,  we will not break the old feature.
