### ISSUE TITLE
feature(sdk): "Loop" DSL extension

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#791]
/kind feature

**Description:**
There are multiple features that `PipelineLoop` offers that are lacking in the original KFP's `dsl.ParallelFor`. The DSL users, therefore, cannot easily use them --- in order to do that they need to first generate yaml from DSL and then modify the resulting yaml accordingly, which isn't always trivial.

My proposal: to introduce a DSL extension for `Loop`. Usage:

```python
# just like dsl.ParallelLoop
with Loop(array, parallelism=5) as item:
  pass

# range, "step" being optional
with Loop(start=1, end=10) as item:
  pass

# with string separator
with Loop(string, separator=",") as item:
  pass

# with "break" capability (what is now last-loop-task)
with Loop(array) as item:
  with dsl.Condition(CEL_ConditionOp(f"{item} == 0")):
    Break()
```

To make the transition a bit easier, it can inherit from dsl.ParallelFor:
```python
_Num = TypeVar('_Num', int, float)
class Loop(dsl.ParallelFor):
  @classmethod
  def sequential(cls,
                 loop_args: _for_loop.ItemList):
    return cls(loop_args, parallelism=1)

  @classmethod
  def from_string(cls,
                  loop_args: Union[str, _pipeline_param.PipelineParam],
                  separator: Optional[str] = None,
                  **,
                  parallelism: Optional[int] = None):
    return cls(loop_args=string, separator=separator, parallelism=parallelism)

  @overload
  @classmethod
  def range(cls,
            start: _Num,
            end: _Num,
            **,
            parallelism: Optional[int] = None): ...
  @overload
  @classmethod
  def range(cls,
            start: _Num,
            step: _Num,
            end: _Num,
            **,
            parallelism: Optional[int] = None): ...

  @classmethod
  def range(cls,
            a: _Num,
            b: _Num,
            c: Optional[_Num] = None,
            **,
            parallelism: Optional[int] = None):
      if c is None:
          return cls(start=a, end=b, parallelism=parallelism)
      else:
          return cls(start=a, step=b, end=c, parallelism=parallelism)

  @overload
  def __init__(self,
               loop_args: _for_loop.ItemList,
               parallelism: Optional[int] = None): ...
  @overload
  def __init__(self,
               loop_args: _pipeline_param.PipelineParam,
               parallelism: Optional[int] = None,
               separator: Optional[str] = None): ...
  @overload
  def __init__(self,
               loop_args: str,
               separator: str,
               parallelism: Optional[int] = None): ...
  @overload
  def __init__(self,
               loop_args: str,
               parallelism: Optional[int] = None,
               **,
               separator: str): ...
  @overload
  def __init__(self,
               **,
               start: _Num,
               end: _Num,
               step: Optional[_Num] = None,
               parallelism: Optional[int] = None): ...

  def __init__(self, *args, **kwargs): ...
```

...which would enable very intuitive and easily-readable syntax:
```python
with Loop.sequential(["a", "b", "c"]):
  pass

with Loop.from_string("a,b,c", separator=","):
  pass

with Loop.range(1, 10):
  pass

with Loop.range(1, 2, 10):
  pass
```

**Additional information:**
Additional advantage: `parallelism` and `separator` could be allowed to accept `PipelineParam`s, currently not possible for dsl.ParallelFor.

**Comment by Tomcli** [comment]
@Udiknedormin for the first two options `ParallelLoop` and `range` makes sense to me. However, the `string separator` and `break` is very specific to the Tekton pipelineloop syntax.

**Comment by Udiknedormin** [comment]
@Tomcli Well, it would be good to provide SOME way of using those in the DSL, as right now using those requires some non-trivial post-processing of the yaml produced by the kfp-tekton compiler.

**Comment by Tomcli** [comment]
I added the base skeleton for the loop extension. It seems like python is not that easy to overload or dispatch a function that's not using native Python type (e.g. python dispatch has difficult time to parse union type). So instead I have all the parameter as optional and have some conditions to check which way we should call the loop.

As part of it, we will create a list of issues to tackle the loop dsl extension issue.
1. Make pipelineloop to break the loop when seeing a "break" task get executed rather than skipped. This way is easier to represent in the DSL using the `Break()` function. https://github.com/kubeflow/kfp-tekton/issues/800
2. Extend or overload _for_loop dsl class to store new attributes such as `separator`, `start`, `end`. This way the compiler can retrieve these information as part of the kfp dsl.
