### ISSUE TITLE
Make pipelineloop to break when seeing a pipelineloop break operation task

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#800]
/kind feature

**Description:**
Currently, pipelineloop can break the loop when it sees a task is getting skipped. However, it would make more sense in the DSL if we can have it to also break the loop when it sees a specific task prefix name. This should be an addition to the current break feature instead of replacing it.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
Currently the pipeline loop break only happens when the task is skipped as below. We want to extend this logic to also check whether any task with `pipelineloop-break-operation` prefix in the task name is executed. If so, we should break the loop as below as well. This way, we can have multiple break tasks in the DSL and all of them will have the task prefix `pipelineloop-break-operation`. 
https://github.com/kubeflow/kfp-tekton/blob/c4f52e5f1c360e577187be6c447b5afc1c0505cb/tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go#L558-L571

**Comment by wzhanw** [comment]
@Tomcli I think breaking the loop when seeing a pipelineloop break operation task is not precise.
I think we need to check its final status and if the task is skipped we should not break the loop.
