### ISSUE TITLE
Pipeline Timeouts set to 0s for the entire pipeline and each component

### ISSUE THREAD

**Issue by peterhaddad3121** [kubeflow/kfp-tekton#811]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I installed Tekton using pip install kfp-tekton, and ran the following code to generate the yaml of a KF pipeline.

```
kfp_tekton.compiler.TektonCompiler().compile(basic_pipeline, "pipeline.yaml")
```

**What did you expect to happen:**

I expected the Pipeline timeouts to be set to nothing, in the outputted yaml, since this was the behavior I was previously seeing with kfp-tekton's sdk. The pipelines get set to 0s.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

I've tried a variety of different versions, and directly followed the documentation in the Readme.

I can specifically set the timeout by running the functions to do so, but I have to do this for each component and never had to perform this type of action previously.

**Environment:**

kfp                      1.7.2
kfp-pipeline-spec        0.1.13
kfp-server-api           1.7.1
kfp-tekton               1.0.1

* Python Version (use `python --version`): I've ran on 3.7, 3.8 and other versions.
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
This is fixed in our master branch a while ago. We will be cutting a new release this week and the new SDK version should solve this problem.

**Comment by Tomcli** [comment]
At the meantime, if you install Tekton v0.27.0 or install whole Kubeflow, this issue can be avoid. The main cause of this issue is due to a regression bug since Tekton v0.28.0.

**Comment by Tomcli** [comment]
The latest v1.1.0 release addressed this issue. Feel free to let us know if you still encounter this problem.
