### ISSUE TITLE
Support Exit handler

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#85]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]
We want to support Exit handler in Tekton. 
Example: https://github.com/kubeflow/pipelines/blob/master/samples/core/exit_handler/exit_handler.py

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]
We probably need to have exit handler support for Tekton.

**Comment by fenglixa** [comment]
Here is the tracking issue in the Tekton community tektoncd/pipeline#2437

**Comment by fenglixa** [comment]
Great thanks to @pritidesai working on this issue of tekton side. It's an important feature, and glad to see tekton is doing that.
For PR #2661, I saw It's been a long time, not sure when it could be finished? It would be great if we could finish it as soon as possible

**Comment by pritidesai** [comment]
@fenglixa it is finished and open for review but recent changes around `PipelineRun Status` has caused conflicts, working on resolving them as I speak 🙏

**Comment by fenglixa** [comment]
Sounds good, thanks @pritidesai .
#180 logged in kfp-tekton to trace the testing of this feature once PR #2661 is done.
