### ISSUE TITLE
Loop.range fails with Cannot determine number of iterations: The from or to parameters was not found in runs

### ISSUE THREAD

**Issue by typeness** [kubeflow/kfp-tekton#902]
/kind bug

**What steps did you take and what happened:**
Using the following DSL

``` py
from kfp import dsl, components
from kfp_tekton.tekton import Loop

op1_yaml = '''\
name: 'my-in-coop1'
inputs:
- {name: item, type: Integer}
- {name: param, type: Integer}
implementation:
    container:
        image: library/bash:4.4.23
        command: ['sh', '-c']
        args:
        - |
          set -e
          echo op1 "$0" "$1"
        - {inputValue: item}
        - {inputValue: param}
'''


@dsl.pipeline(name='pipeline')
def pipeline():
    with Loop.range(start=-1, step=1, end=1) as item:
        op1_template = components.load_component_from_text(op1_yaml)
        op1 = op1_template(item, 10)

if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  from kfp_tekton.compiler.pipeline_utils import TektonPipelineConf
  tekton_pipeline_conf = TektonPipelineConf()
  tekton_pipeline_conf.set_tekton_inline_spec(True)
  # tekton_pipeline_conf.set_resource_in_separate_yaml(True)
  Compiler().compile(pipeline, __file__.replace('.py', '.yaml'), tekton_pipeline_conf=tekton_pipeline_conf)

```

pipeline loop fails in runtime with the error message 

> "type":"Succeeded",
> "status":"False",
> "lastTransitionTime":"2022-03-31T22:22:55Z",
> "reason":"PipelineLoopValidationFailed",
> "message":"Cannot determine number of iterations: The from or to parameters was not found in runs"
> 

This also happens for the following cases
- (start=-1, step=1, end=0)
- (start=-1, step=0, end=0)
- (start=1, step=1, end=-1)
- (start=0, step=1, end=-1)
- (start=-1, step=1, end=-1)
- (start=1, step=0, end=-1)
- (start=0, step=0, end=-1)
- (start=1, step=-1, end=-1)
- (start=0, step=-1, end=-1)

**What did you expect to happen:**

I expect the loop to iterate successfully.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by ScrapCodes** [comment]
Currently we do not support start from/to as -ve integers. 

Is this a requirement?

**Comment by Udiknedormin** [comment]
@ScrapCodes It is, yes.

**Comment by yhwang** [comment]
/assign @ScrapCodes
Thanks Prashant
