### ISSUE TITLE
Leverage the minimal pipelinerun status from Tekton 0.35 to reduce the yaml size in k8s ETCD

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#931]
/kind feature

**Description:**
Tekton 0.35 now has new features to minimize taskrun and run status on pipelinerun, but need to update kfp-tekton and ui to fetch these status using another k8s api calls.

If we leverage this features on KFP, we can run more tasks per pipeline. However, this will have few millisecond delay on the pipeline api and ui status update since this feature will need extra k8s api to calls fetch all the information we have before.

Feature details are in the TEP 100 in this release note:
https://github.com/tektoncd/pipeline/releases/tag/v0.35.0

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Tomcli** [comment]
Since the UI is relying on the backend API to give back the pipelinerun yaml, if we can merge the embedded pipelinerun status with the necessary information from each taskrun/run, we might able to make this feature work by only updating the pipelinerun resource fetching logic.

**Comment by yhwang** [comment]
added #1039 to support pipelineloop in the persistence agent to store nested taskruns/runs statuses into the backend datastore.
