### ISSUE TITLE
Support job parameter name with '$' character

### ISSUE THREAD

**Issue by xawangyd** [kubeflow/kfp-tekton#934]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]

Currently our important customers need to use parameter with dynamic name like $APT_DISABLE_COMBINATION , from the doc https://tekton.dev/docs/pipelines/pipelines/#specifying-parameters seems kfp-tekton does not support such usage.
Hope kfp-tekton can support such feature, that will be very helpful for our customers.

Thanks

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

   ```
             {
                  "type": "String",
                  "group": "job_parameters",
                  "value": "True",
                  "name": "$APT_DISABLE_COMBINATION",
                  "human_name": "Job Parameter $APT_DISABLE_COMBINATION"
                },
                {
                  "type": "String",
                  "group": "job_parameters",
                  "value": "$Ev_MEMSQL_SCHEMA",
                  "name": "$Ev_MEMSQL_SCHEMA",
                  "human_name": "Job Parameter $Ev_MEMSQL_SCHEMA"
                },
```
```
results:
  - name: job-parameters
    value: '{"$APT_DISABLE_COMBINATION": private.literals.lit_0, "$Ev_MEMSQL_SCHEMA":
      private.literals.lit_1, "$Ev_MEMSQL_USER": private.literals.lit_2, "$Ev_MEMSQL_PWD":
      private.literals.lit_3, "$Ev_PATH_FFD_BASE": private.literals.lit_4, "Ps_COMMON_PARAMS":
      private.literals.lit_5, "P_BUS_DATE": private.literals.lit_6, "P_MEMSQL_TABLE":
      private.literals.lit_7, "P_LOOKUP_COLUMN": private.literals.lit_8, "$APT_GRID_COMPUTENODES":
      private.literals.lit_9, "$APT_GRID_PARTITIONS": private.literals.lit_10, "$APT_GRID_QUEUE":
      private.literals.lit_11, "P_SORT_ORDER": private.literals.lit_12, "P_STATE_CODE":
      private.literals.lit_13, "P_COUNTER": private.literals.lit_14, "P_FFD_MEMSQL_HOSTS":
      private.literals.lit_15, "$Ev_MEMSQL_CLASS_PATH": private.literals.lit_16,
...
```

**Comment by Tomcli** [comment]
@xawangyd If you can see in the Tekton docs, the parameter name has to be static. Only the parameter value can be dynamic in this case. Is your use case is to also have the parameter name be dynamic?

@Udiknedormin Do you think this is something can be mapped within the Watson Studio pipelines? Within the Python DSL level, the parameter name can be referred as a python string variable. But in Tekton yaml currently all parameter names have to be static.

**Comment by xawangyd** [comment]
Hi @Tomcli 
It is just a static parameter name contains ` $ `character. Not a dynamic name. No need to be dynamic for the parameter name.

**Comment by xawangyd** [comment]
Based on our discussion, seems no need this enhancement on kfp-tekton side.
Thanks everyone.
