### ISSUE TITLE
Loop.range generates inconsistent number of iterations when start=end

### ISSUE THREAD

**Issue by typeness** [kubeflow/kfp-tekton#935]
/kind bug

**What steps did you take and what happened:**

Reproduce using the following code

``` python
from kfp import dsl, components
from kfp_tekton.tekton import Loop

op1_yaml = '''\
name: 'my-in-coop1'
inputs:
- {name: item, type: Integer}
- {name: param, type: Integer}
implementation:
    container:
        image: library/bash:4.4.23
        command: ['sh', '-c']
        args:
        - |
          set -e
          echo op1 "$0" "$1"
        - {inputValue: item}
        - {inputValue: param}
'''


@dsl.pipeline(name='pipeline')
def pipeline():
    with Loop.range(start=0, step=1, end=0) as item:
        op1_template = components.load_component_from_text(op1_yaml)
        op1 = op1_template(item, 10)

if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  from kfp_tekton.compiler.pipeline_utils import TektonPipelineConf
  tekton_pipeline_conf = TektonPipelineConf()
  tekton_pipeline_conf.set_tekton_inline_spec(True)
  # tekton_pipeline_conf.set_resource_in_separate_yaml(True)
  Compiler().compile(pipeline, __file__.replace('.py', '.yaml'), tekton_pipeline_conf=tekton_pipeline_conf)
```

This generates 0 iterations.

**What did you expect to happen:**
I expect this to generate 1 iteration given that the loop `Loop.range(start=0, step=1, end=1)` generates 2 iterations.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
/assign @ScrapCodes 

@ScrapCodes are you able to take over this issue?

**Comment by ScrapCodes** [comment]
Are you sure, if start = end = 0, and step = 1 then generate one iteration?
If start = 0 and end =1, step = 1, then generate two iteration seems like a bug to me. WDYT?
@Tomcli, @yhwang and @typeness

**Comment by yhwang** [comment]
to summarize, correct me if I am wrong,
Current behaviors:
- start = end = 0, and step = 1:
  0 iteration
- start=0, step=1, end=1:
  2 iterations

for me, I think the following behaviors make sense to me:
- start = end = 0, and step = 1:
  0 iteration
- start=0, step=1, end=1:
  1 iteration

**Comment by Tomcli** [comment]
I think what DataStage wants is not the exact behavior of Python range. It's similar to the requirement of enumerate where the index is counted from 1 instead of 0. 

@Udiknedormin start = 0 end = 0, and step = n should be always one iteration in this case right?

**Comment by Tomcli** [comment]
yes we should

**Comment by ScrapCodes** [comment]
Is it true 

> I think what DataStage wants is not the exact behavior of Python range. It's similar to the requirement of enumerate where the index is counted from 1 instead of 0.
> 
> @Udiknedormin start = 0 end = 0, and step = n should be always one iteration in this case right?

Is it true of any start e.g. start = 1 and end =1 , should also generate one iteration.
