### ISSUE TITLE
Extend resourceOp warpper image to have multiple outputs

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#94]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]
As of today, the kube-client wrapper only takes the output as a string list and output those in a single output file. https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/tests/compiler/testdata/resourceop_basic.yaml#L84-L85

However, in ideally solution, we should input a dictionary of output name and output variables. Then the wrapper should save each of those variables in an individual output file under /tekton/results.

Right now, I have a temporary step for adding the volumeop information to the results using an extra step. But ideally we should able to use the resourceOp generated results without that extra step. https://github.com/kubeflow/kfp-tekton/pull/93/files#diff-cb633bb266cb10fcc88b8633ffdf50d8R199-R220

This feature could be somewhat challenging. @fenglixa @vincent-pli Let me know what you guys think and we could discuss how we can approach this.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by vincent-pli** [comment]
@Tomcli 
Since `params` of `tekton` only support `string`, `array` no `structure`, so we can still use string but make it looks like a structure, like this:
```
  - name: output
    value: |
      - name: job-name
        valueFrom: '{.metadata.name}'
      - name: job-namespace
        valueFrom: '{.metadata.namespace}' 
```
What do you think?

**Comment by Tomcli** [comment]
@vincent-pli Sure, for the output param we can use any format because we have control of the compiler. However, what we really want to see is the `kubectl-wrapper` can produce each of those output as an individual result file following the tekton [execution results requirement](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#storing-execution-results). We can  provide the name of each result along with what value we are looking for.

We also have some edge cases where valueFrom can be '{}', in this case you can just create a blank file for that execution result. We also have edge cases in VolumeSnapshotOp where we need to get output from the [status field](https://github.com/kubeflow/pipelines/blob/master/sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml#L91-L93)
https://github.com/kubeflow/pipelines/blob/master/sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml#L91-L93. Do you think you can include these edge cases in your task? Thank you.

**Comment by vincent-pli** [comment]
@Tomcli 
For the `individual result file`, for now it's already support.
For the `{}` and `blank`. since output expression will be use in `kubectl get -o jsonpath=$(output-express)`, so you could define express as "{.metadata.placeholder}", then the command will get a `""` and a blank file will be created.

**Comment by Tomcli** [comment]
Thanks @vincent-pli, then in that case we just need to make sure the `output` is also taking the result names so we know what are the results we should map to within the compiler. 
```
  - name: output
    value: |
      - name: job-name
        valueFrom: '{.metadata.name}'
      - name: job-namespace
        valueFrom: '{.metadata.namespace}' 
```
is this string format already supported in your kubectl-wrapper?

**Comment by vincent-pli** [comment]
@Tomcli 
Yes, it already works, you can take a try with the sample:
https://github.com/vincent-pli/kubectl-wrapper/tree/master/deploy

**Comment by Tomcli** [comment]
@vincent-pli, overall it looks great, although I found a bug when passing it as results. Can you remove all the quote when you store them as file?
```
  taskResults:
  - name: manifest
    value: '"map[apiVersion:v1 kind:PersistentVolumeClaim metadata:map[annotations:map[ibm.io/provisioning-status:failed:
      \"ReadWriteMany\" is an unsupported access mode. Block Storage supports only
      ''ReadWriteOnce'' mode rok/origin:test volume.beta.kubernetes.io/storage-provisioner:ibm.io/ibmc-block]
      creationTimestamp:2020-04-16T20:31:39Z finalizers:[kubernetes.io/pvc-protection]
      name:volumesnapshotop-rokurl-run-6hw8m-vol1 namespace:default resourceVersion:26481100
      selfLink:/api/v1/namespaces/default/persistentvolumeclaims/volumesnapshotop-rokurl-run-6hw8m-vol1
      uid:d340b4ca-730c-4a1a-ac4d-938ba3398bd1] spec:map[accessModes:[ReadWriteMany]
      resources:map[requests:map[storage:1Gi]] storageClassName:ibmc-block-gold volumeMode:Filesystem]
      status:map[phase:Pending]]"'
  - name: name
    value: '"volumesnapshotop-rokurl-run-6hw8m-vol1"'
  - name: size
    value: '""'
```

**Comment by Tomcli** [comment]
right now the extra `"` is also stored as results which is causing some errors.

**Comment by vincent-pli** [comment]
@Tomcli 
Thanks for catching, I have enhanced the code, please take a try.

**Comment by Tomcli** [comment]
Thanks @vincent-pli, it works great. We can put this into tekton catalog now so that this task can be official.

**Comment by vincent-pli** [comment]
@Tomcli 
There still one thing, I talked with @Vdemeester from `tekton`, he think the `catalog` should only maintain the `yaml`s stuff, the source code will make the repo mass to manage. 

So we still need find a more official repo.

Another choice is submit the image to a official repo.
@animeshsingh @ckadner @fenglixa
