### ISSUE TITLE
Loop(dsl.ParallelFor) doesn't have any method of editing its metadata

### ISSUE THREAD

**Issue by wzhanw** [kubeflow/kfp-tekton#986]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]
We like to provide custom labels and annotations for the loop, then the loop can pass down those labels to its sub-pipeline task.
But the current Loop(dsl.ParallelFor) doesn't have any method of editing its metadata.
Without this support we have to go for post-processing, which is too painful and buggy. 

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by wzhanw** [comment]
@Tomcli could you validate this requirement and approve this feature enhancement? Thanks.

**Comment by Tomcli** [comment]
Sure it make sense to me. We can try to see can it be added to the Loop class
https://github.com/kubeflow/kfp-tekton/blob/master/sdk/python/kfp_tekton/tekton.py#L235
